@include('frontend.cratesOnSkates.components.main_header')
    @include('frontend.cratesOnSkates.components.nav') 
        @yield('pageContent')
    @include('frontend.cratesOnSkates.components.footer')
@include('frontend.cratesOnSkates.components.main_footer')