<?php

use Illuminate\Database\Seeder;

class CmsComponentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        \DB::statement('set foreign_key_checks = 0');
        \DB::table('cms_components')->delete();
        \DB::statement('set foreign_key_checks = 1');
        
        \DB::table('cms_components')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'slider',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 14:57:35',
                'updated_at' => '2019-11-20 14:57:35',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'about us title content',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:05:07',
                'updated_at' => '2019-11-20 15:05:07',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'consultation form',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:09:35',
                'updated_at' => '2019-11-20 15:09:35',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'recent works',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:10:00',
                'updated_at' => '2019-11-20 15:10:00',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'promo video',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:11:03',
                'updated_at' => '2019-11-20 15:11:03',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'biography',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:11:31',
                'updated_at' => '2019-11-20 15:11:31',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'project counter',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:12:03',
                'updated_at' => '2019-11-20 15:12:03',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'brand client',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:13:49',
                'updated_at' => '2019-11-20 15:13:49',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'services banner',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:37:40',
                'updated_at' => '2019-11-20 16:37:40',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'services content',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:10:50',
                'updated_at' => '2019-11-20 17:10:50',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'testimonial',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:19:21',
                'updated_at' => '2019-11-20 17:19:21',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'portfolio banner',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:21:36',
                'updated_at' => '2019-11-20 17:21:36',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'portfolio latest work',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:21:50',
                'updated_at' => '2019-11-20 17:21:50',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'blog banner',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:22:57',
                'updated_at' => '2019-11-20 17:22:57',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'blog left content',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:23:06',
                'updated_at' => '2019-11-20 17:23:06',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'blog right content',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:23:15',
                'updated_at' => '2019-11-20 17:23:15',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'about us banner',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:25:20',
                'updated_at' => '2019-11-20 17:25:20',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'about us team member',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:25:42',
                'updated_at' => '2019-11-20 17:25:42',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'career banner',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:27:15',
                'updated_at' => '2019-11-20 17:27:15',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'career content',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:27:22',
                'updated_at' => '2019-11-20 17:27:22',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'pricing banner',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:28:34',
                'updated_at' => '2019-11-20 17:28:34',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'pricing table',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:28:42',
                'updated_at' => '2019-11-20 17:28:42',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'single career',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:30:38',
                'updated_at' => '2019-11-20 17:30:38',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'single team banner',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:32:08',
                'updated_at' => '2019-11-20 17:32:08',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'specialization',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:32:21',
                'updated_at' => '2019-11-20 17:32:21',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'specialization right content',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:32:35',
                'updated_at' => '2019-11-20 17:32:35',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'contact banner',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:34:02',
                'updated_at' => '2019-11-20 17:34:02',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'contact info',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:34:11',
                'updated_at' => '2019-11-20 17:34:11',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'contact form',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:34:25',
                'updated_at' => '2019-11-20 17:34:25',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'newsletter',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:34:35',
                'updated_at' => '2019-11-20 17:34:35',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'error page banner',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:36:10',
                'updated_at' => '2019-11-20 17:36:10',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'error page content',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:36:17',
                'updated_at' => '2019-11-20 17:36:17',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'single team info',
                'template_id' => 3,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:41:01',
                'updated_at' => '2019-11-21 13:41:01',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'home first',
                'template_id' => 4,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 18:33:21',
                'updated_at' => '2019-11-29 18:33:21',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'working process',
                'template_id' => 4,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 19:01:00',
                'updated_at' => '2019-11-29 19:01:00',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'recyclable moving box',
                'template_id' => 4,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 19:01:10',
                'updated_at' => '2019-11-29 19:01:10',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'customer tape',
                'template_id' => 4,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 19:01:28',
                'updated_at' => '2019-11-29 19:01:28',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'about our crates',
                'template_id' => 4,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 19:02:01',
                'updated_at' => '2019-11-29 19:02:01',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'commercial mover',
                'template_id' => 4,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-13 17:14:13',
                'updated_at' => '2019-12-13 17:14:13',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'commercial form',
                'template_id' => 4,
                'location' => 'home',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-13 17:32:36',
                'updated_at' => '2019-12-13 17:32:36',
            ),
        ));
        
        
    }
}