<?php

use Illuminate\Database\Seeder;

class CmsFilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cms_files')->delete();
        
        \DB::table('cms_files')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type' => 'post',
                'file_name' => 'd5d36511d1ae1d00cfbd64047854a8b7.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 14:58:55',
                'updated_at' => '2019-11-20 14:58:55',
            ),
            1 => 
            array (
                'id' => 2,
                'type' => 'post',
                'file_name' => 'f535027f13b1757c93684a347ceb3e62.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:00:19',
                'updated_at' => '2019-11-20 15:00:19',
            ),
            2 => 
            array (
                'id' => 3,
                'type' => 'post',
                'file_name' => '8cce9eed4427ec11128807d23f7998e0.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:01:06',
                'updated_at' => '2019-11-20 15:01:06',
            ),
            3 => 
            array (
                'id' => 4,
                'type' => 'post',
                'file_name' => 'c93d469de127aea6524fe542e1ad0dc8.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:42:06',
                'updated_at' => '2019-11-20 16:42:06',
            ),
            4 => 
            array (
                'id' => 5,
                'type' => 'post',
                'file_name' => '65e7f3973f198bf32b8c53801cfc49fa.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:47:05',
                'updated_at' => '2019-11-20 16:47:05',
            ),
            5 => 
            array (
                'id' => 6,
                'type' => 'post',
                'file_name' => '48875c1f78565ae12e3102d8f67fb957.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 6,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:51:11',
                'updated_at' => '2019-11-20 16:51:11',
            ),
            6 => 
            array (
                'id' => 7,
                'type' => 'post',
                'file_name' => 'efead5f27b5324fe94df75bb11758fec.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 7,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:51:40',
                'updated_at' => '2019-11-20 16:51:40',
            ),
            7 => 
            array (
                'id' => 8,
                'type' => 'post',
                'file_name' => 'a59984306f4abe566f7a8460e13f95c6.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 8,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:52:00',
                'updated_at' => '2019-11-20 16:52:00',
            ),
            8 => 
            array (
                'id' => 9,
                'type' => 'post',
                'file_name' => '66bd9f467f2fac8a5d3a677b07cbc906.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 9,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:52:23',
                'updated_at' => '2019-11-20 16:52:23',
            ),
            9 => 
            array (
                'id' => 10,
                'type' => 'post',
                'file_name' => 'ec01109a29da15e5281178bf7ce29cb9.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 10,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:52:44',
                'updated_at' => '2019-11-20 16:52:44',
            ),
            10 => 
            array (
                'id' => 11,
                'type' => 'post',
                'file_name' => 'e29a4cac887ed39ad11e7224533989dd.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 11,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:53:14',
                'updated_at' => '2019-11-20 16:53:14',
            ),
            11 => 
            array (
                'id' => 12,
                'type' => 'post',
                'file_name' => '7e308762a02c9af435ecb70eab2f1af6.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 12,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:55:14',
                'updated_at' => '2019-11-20 16:55:14',
            ),
            12 => 
            array (
                'id' => 13,
                'type' => 'post',
                'file_name' => 'a712dba49be959cf3e2ac00dd388ab77.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 17,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:03:05',
                'updated_at' => '2019-11-20 17:03:05',
            ),
            13 => 
            array (
                'id' => 14,
                'type' => 'post',
                'file_name' => 'fb740639789dad6b0c7b23c3e374dc70.png',
                'table_name' => 'cms_posts',
                'table_id' => 18,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:05:42',
                'updated_at' => '2019-11-20 17:05:42',
            ),
            14 => 
            array (
                'id' => 15,
                'type' => 'post',
                'file_name' => 'f0fecc301a45ddf8f5f6aa6189473a43.png',
                'table_name' => 'cms_posts',
                'table_id' => 19,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:06:20',
                'updated_at' => '2019-11-20 17:06:20',
            ),
            15 => 
            array (
                'id' => 16,
                'type' => 'post',
                'file_name' => 'da2c9171a070c7f5613f137b266a6c4e.png',
                'table_name' => 'cms_posts',
                'table_id' => 20,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:06:46',
                'updated_at' => '2019-11-20 17:06:46',
            ),
            16 => 
            array (
                'id' => 17,
                'type' => 'post',
                'file_name' => '6d2e348e8af56dab0872e0d84797a1b2.png',
                'table_name' => 'cms_posts',
                'table_id' => 21,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:07:16',
                'updated_at' => '2019-11-20 17:07:16',
            ),
            17 => 
            array (
                'id' => 18,
                'type' => 'post',
                'file_name' => 'da09f368aeb2393d58c90c72818db92e.png',
                'table_name' => 'cms_posts',
                'table_id' => 22,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:08:14',
                'updated_at' => '2019-11-20 17:08:14',
            ),
            18 => 
            array (
                'id' => 19,
                'type' => 'post',
                'file_name' => '6e371a4092d495a9725ea5f5048b3b2d.png',
                'table_name' => 'cms_posts',
                'table_id' => 23,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:08:35',
                'updated_at' => '2019-11-20 17:08:35',
            ),
            19 => 
            array (
                'id' => 20,
                'type' => 'post',
                'file_name' => '5b69b779547e045ac3c922a1fbfce46a.png',
                'table_name' => 'cms_posts',
                'table_id' => 24,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:09:29',
                'updated_at' => '2019-11-20 17:09:29',
            ),
            20 => 
            array (
                'id' => 21,
                'type' => 'post',
                'file_name' => 'c4bb4325e53bc33b74935b42fbf07c70.png',
                'table_name' => 'cms_posts',
                'table_id' => 25,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:09:51',
                'updated_at' => '2019-11-20 17:09:51',
            ),
            21 => 
            array (
                'id' => 22,
                'type' => 'post',
                'file_name' => '64c9b2bf0e729ed91d47fd42071d2a9c.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 26,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:13:38',
                'updated_at' => '2019-11-20 17:13:38',
            ),
            22 => 
            array (
                'id' => 23,
                'type' => 'post',
                'file_name' => '1dcab953663507c947fea981afcc576d.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 27,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:50:20',
                'updated_at' => '2019-11-20 17:50:20',
            ),
            23 => 
            array (
                'id' => 24,
                'type' => 'post',
                'file_name' => 'cdf762df39b66b6576b372d75b72b2e5.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 28,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 19:37:51',
                'updated_at' => '2019-11-20 19:37:51',
            ),
            24 => 
            array (
                'id' => 25,
                'type' => 'post',
                'file_name' => 'd0e1efb14d43862586ab0d0505f322cd.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 29,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 19:38:25',
                'updated_at' => '2019-11-20 19:38:25',
            ),
            25 => 
            array (
                'id' => 26,
                'type' => 'post',
                'file_name' => '9638bf164a348d5b8cad2f52f7f84052.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 30,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 19:39:14',
                'updated_at' => '2019-11-20 19:39:14',
            ),
            26 => 
            array (
                'id' => 27,
                'type' => 'post',
                'file_name' => 'fc31a35e44316928fb56460d9550168d.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 31,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 19:39:55',
                'updated_at' => '2019-11-20 19:39:55',
            ),
            27 => 
            array (
                'id' => 28,
                'type' => 'post',
                'file_name' => 'f24bbf88d6c396ed08b891d0f43b716b.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 32,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 12:20:27',
                'updated_at' => '2019-11-21 12:20:27',
            ),
            28 => 
            array (
                'id' => 29,
                'type' => 'post',
                'file_name' => 'b516d944fc31f0971778db21d59d6ae7.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 33,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 12:28:01',
                'updated_at' => '2019-11-21 12:28:01',
            ),
            29 => 
            array (
                'id' => 30,
                'type' => 'post',
                'file_name' => 'ea6d7a5b3fd2ac2247ef821ef90e925c.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 34,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:43:42',
                'updated_at' => '2019-11-21 13:43:42',
            ),
            30 => 
            array (
                'id' => 31,
                'type' => 'post',
                'file_name' => 'a8cbe6621efb9897d18368b67a8d58fc.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 36,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:52:17',
                'updated_at' => '2019-11-21 13:52:17',
            ),
            31 => 
            array (
                'id' => 32,
                'type' => 'post',
                'file_name' => '3de256d83d24d8a22d6d524c2a2f20a9.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 37,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:56:17',
                'updated_at' => '2019-11-21 13:56:17',
            ),
            32 => 
            array (
                'id' => 33,
                'type' => 'post',
                'file_name' => '9acb2c625c8b59f1871bf50832f0046e.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 38,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:59:13',
                'updated_at' => '2019-11-21 13:59:13',
            ),
            33 => 
            array (
                'id' => 34,
                'type' => 'post',
                'file_name' => 'babac728eff4e265c5a27b0e85f5967b.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 39,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 14:03:09',
                'updated_at' => '2019-11-21 14:03:09',
            ),
            34 => 
            array (
                'id' => 35,
                'type' => 'preview',
                'file_name' => '4b6fde4a5a4344609159f72fc678d856.PNG',
                'table_name' => 'cms_templates',
                'table_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 15:28:48',
                'updated_at' => '2019-11-21 15:28:48',
            ),
            35 => 
            array (
                'id' => 36,
                'type' => 'post',
                'file_name' => 'dfc5db762296c65f9833f0dd5f5644cf.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 43,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-25 14:10:15',
                'updated_at' => '2019-11-25 14:10:15',
            ),
            36 => 
            array (
                'id' => 37,
                'type' => 'post',
                'file_name' => '8e31c681eabeffaecfef2c35b65d56b0.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 40,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-25 14:11:25',
                'updated_at' => '2019-11-25 14:11:25',
            ),
            37 => 
            array (
                'id' => 38,
                'type' => 'post',
                'file_name' => '6f48121e08892d6b0256ba69f2c4bded.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 48,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-25 14:13:22',
                'updated_at' => '2019-11-25 14:13:22',
            ),
            38 => 
            array (
                'id' => 39,
                'type' => 'post',
                'file_name' => 'b652c7a47cfe97172ecad8c83f076e9d.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 49,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-25 14:13:35',
                'updated_at' => '2019-11-25 14:13:35',
            ),
            39 => 
            array (
                'id' => 40,
                'type' => 'post',
                'file_name' => '9a3c922a0b3eca1f057b6871c426e784.jpg',
                'table_name' => 'cms_posts',
                'table_id' => 54,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-25 14:14:15',
                'updated_at' => '2019-11-25 14:14:15',
            ),
        ));
        
        
    }
}