<?php

use Illuminate\Database\Seeder;

class CmsMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        \DB::statement('set foreign_key_checks = 0');
        \DB::table('cms_menus')->delete();
        \DB::statement('set foreign_key_checks = 1');
        \DB::table('cms_menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Home',
                'route' => NULL,
                'is_parent' => 1,
                'template_id' => 3,
                'parent_id' => NULL,
                'seq_no' => 1,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 16:26:15',
                'updated_at' => '2019-11-22 12:11:16',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Services',
                'route' => '/netlifytemp/services',
                'is_parent' => 1,
                'template_id' => 3,
                'parent_id' => NULL,
                'seq_no' => 2,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 17:49:33',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Portfolio',
                'route' => NULL,
                'is_parent' => 1,
                'template_id' => 3,
                'parent_id' => NULL,
                'seq_no' => 3,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 19:17:33',
                'updated_at' => '2019-11-21 19:48:10',
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'Features',
                'route' => NULL,
                'is_parent' => 1,
                'template_id' => 3,
                'parent_id' => NULL,
                'seq_no' => 4,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 19:19:47',
                'updated_at' => '2019-11-21 19:48:49',
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'Blog Page',
                'route' => NULL,
                'is_parent' => 1,
                'template_id' => 3,
                'parent_id' => NULL,
                'seq_no' => 5,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 19:21:11',
                'updated_at' => '2019-11-21 19:48:59',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'Contact Us',
                'route' => '/netlifytemp/contact',
                'is_parent' => 1,
                'template_id' => 3,
                'parent_id' => NULL,
                'seq_no' => 6,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 19:49:43',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'Home One',
                'route' => '/netlifytemp',
                'is_parent' => 0,
                'template_id' => 3,
                'parent_id' => 1,
                'seq_no' => 1,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 19:53:28',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'Portfolio Col 2',
                'route' => '/netlifytemp/portfolio',
                'is_parent' => 0,
                'template_id' => 3,
                'parent_id' => 3,
                'seq_no' => 1,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 12:34:19',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'Blog Page',
                'route' => '/netlifytemp/blog',
                'is_parent' => 0,
                'template_id' => 3,
                'parent_id' => 6,
                'seq_no' => 1,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 12:36:16',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'About Us',
                'route' => '/netlifytemp/about',
                'is_parent' => 0,
                'template_id' => 3,
                'parent_id' => 5,
                'seq_no' => 1,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 12:37:06',
                'updated_at' => '2019-12-06 13:05:15',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'Pricing',
                'route' => '/netlifytemp/pricing',
                'is_parent' => 0,
                'template_id' => 3,
                'parent_id' => 5,
                'seq_no' => 2,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 12:37:35',
                'updated_at' => '2019-12-06 13:05:15',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'Career',
                'route' => '/netlifytemp/career',
                'is_parent' => 0,
                'template_id' => 3,
                'parent_id' => 5,
                'seq_no' => 3,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 12:40:28',
                'updated_at' => '2019-11-22 14:43:54',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'Single Career',
                'route' => '/netlifytemp/singlecareer',
                'is_parent' => 0,
                'template_id' => 3,
                'parent_id' => 5,
                'seq_no' => 4,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 12:41:00',
                'updated_at' => '2019-11-22 14:43:56',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'Single Team',
                'route' => '/netlifytemp/singleteam',
                'is_parent' => 0,
                'template_id' => 3,
                'parent_id' => 5,
                'seq_no' => 5,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 12:41:39',
                'updated_at' => '2019-11-22 14:43:57',
            ),
            14 => 
            array (
                'id' => 16,
                'name' => '404',
                'route' => '/netlifytemp/error',
                'is_parent' => 0,
                'template_id' => 3,
                'parent_id' => 5,
                'seq_no' => 6,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 12:42:04',
                'updated_at' => '2019-11-22 14:43:57',
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'Residential',
                'route' => '/cratesonskates/residential',
                'is_parent' => 1,
                'template_id' => 4,
                'parent_id' => NULL,
                'seq_no' => 2,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 12:19:41',
                'updated_at' => '2019-12-19 13:41:29',
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'Office',
                'route' => '/cratesonskates/office',
                'is_parent' => 1,
                'template_id' => 4,
                'parent_id' => NULL,
                'seq_no' => 3,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 16:57:37',
                'updated_at' => '2019-12-19 13:40:37',
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'Products',
                'route' => '/cratesonskates/products',
                'is_parent' => 1,
                'template_id' => 4,
                'parent_id' => NULL,
                'seq_no' => 4,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 16:58:03',
                'updated_at' => '2019-12-19 13:40:33',
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'About',
                'route' => '/cratesonskates/about',
                'is_parent' => 0,
                'template_id' => 4,
                'parent_id' => 0,
                'seq_no' => 4,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 16:58:14',
                'updated_at' => '2019-12-13 16:39:16',
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'Contact',
                'route' => '/cratesonskates/contact',
                'is_parent' => 1,
                'template_id' => 4,
                'parent_id' => NULL,
                'seq_no' => 6,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 16:58:21',
                'updated_at' => '2019-12-19 13:40:20',
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'Faq',
                'route' => '/cratesonskates/faq',
                'is_parent' => 1,
                'template_id' => 4,
                'parent_id' => NULL,
                'seq_no' => 7,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 16:58:31',
                'updated_at' => '2019-12-19 13:40:15',
            ),
            21 => 
            array (
                'id' => 24,
                'name' => 'Login',
                'route' => '/cratesonskates/login',
                'is_parent' => 1,
                'template_id' => 4,
                'parent_id' => NULL,
                'seq_no' => 8,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-10 18:54:17',
                'updated_at' => '2019-12-19 13:40:07',
            ),
            22 => 
            array (
                'id' => 25,
                'name' => 'Commercial',
                'route' => '/cratesonskates/commercial',
                'is_parent' => 1,
                'template_id' => 4,
                'parent_id' => NULL,
                'seq_no' => 5,
                'icon' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-13 16:37:31',
                'updated_at' => '2019-12-19 13:40:26',
            ),
            // 23 => 
            // array (
            //     'id' => 27,
            //     'name' => 'Dashboard',
            //     'route' => '/cratesonskates/dashboard',
            //     'is_parent' => 1,
            //     'template_id' => 4,
            //     'parent_id' => NULL,
            //     'seq_no' => 1,
            //     'icon' => NULL,
            //     'is_active' => 0,
            //     'is_deleted' => 0,
            //     'userc_id' => 1,
            //     'useru_id' => 1,
            //     'userd_id' => NULL,
            //     'deleted_at' => NULL,
            //     'created_at' => '2019-12-13 18:09:11',
            //     'updated_at' => '2019-12-19 13:41:23',
            // ),
            // 24 => 
            // array (
            //     'id' => 28,
            //     'name' => 'Register',
            //     'route' => '/cratesonskates/register',
            //     'is_parent' => 1,
            //     'template_id' => 4,
            //     'parent_id' => NULL,
            //     'seq_no' => 9,
            //     'icon' => NULL,
            //     'is_active' => 0,
            //     'is_deleted' => 0,
            //     'userc_id' => 1,
            //     'useru_id' => NULL,
            //     'userd_id' => NULL,
            //     'deleted_at' => NULL,
            //     'created_at' => '2019-12-24 18:59:21',
            //     'updated_at' => NULL,
            // ),
        ));
        
        
    }
}