<?php

use Illuminate\Database\Seeder;

class CmsPostsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::statement('SET foreign_key_checks = 0');

        \DB::table('cms_posts')->delete();
        \DB::statement('SET foreign_key_checks = 1');


        \DB::table('cms_posts')->insert(array(
            0 =>
            array(
                'id' => 1,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 1,
                'title' => 'Web Development',
                'sub_title' => 'West is a digital studio founded in London. We\'ve grown and expanded our services,offering of services and solutions Worldwide.',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 14:58:55',
                'updated_at' => '2019-11-20 14:58:55',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            1 =>
            array(
                'id' => 2,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 1,
                'title' => 'WE MAKE GOOD UX DESIGNS',
                'sub_title' => 'West is a digital studio founded in London. We\'ve grown and expanded our services,offering of services and solutions.',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:00:19',
                'updated_at' => '2019-11-20 15:00:19',
                'seq_no' => 2,
                'link_url' => NULL,
            ),
            2 =>
            array(
                'id' => 3,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 1,
                'title' => 'WE MAKE GOOD UX DESIGNS',
                'sub_title' => 'West is a digital studio founded in London. We\'ve grown and expanded our services,offering of services and solutions.',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 15:01:06',
                'updated_at' => '2019-11-20 15:01:06',
                'seq_no' => 3,
                'link_url' => NULL,
            ),
            3 =>
            array(
                'id' => 4,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 2,
                'title' => 'About Us',
                'sub_title' => 'Why We Are The Best?',
                'highlight' => 'We’re Dynamic team of talented people of innovative & marketing expert.',
                'content' => NULL,
                'description' => '<p style="margin-right: 0px; margin-bottom: 25px; margin-left: 0px; color: rgb(51, 51, 51); font-family: Roboto, sans-serif; font-size: 16px;">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years.</p><p style="margin-right: 0px; margin-bottom: 0px; margin-left: 0px; color: rgb(51, 51, 51); font-family: Roboto, sans-serif; font-size: 16px;">content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their sites still in their infancy. Various versions have evolved over the years.</p>',
                'short_description' => 'We Are Best Digital Agency in Asia',
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:42:06',
                'updated_at' => '2019-11-20 16:42:06',
                'seq_no' => 1,
                'link_url' => 'https://www.youtube.com/watch?v=dBlBYP1pQgE',
            ),
            4 =>
            array(
                'id' => 5,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 3,
                'title' => 'Request a free consultation',
                'sub_title' => NULL,
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:47:05',
                'updated_at' => '2019-11-20 16:47:05',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            5 =>
            array(
                'id' => 6,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 4,
                'title' => 'Web Design',
                'sub_title' => 'Lorem ipsum dolor sit amet, consetur adipiscing elit. Aliquam enim enim, pharetra in sodales at, interdum sit',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:51:11',
                'updated_at' => '2019-11-20 16:51:11',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            6 =>
            array(
                'id' => 7,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 4,
                'title' => 'Web Design',
                'sub_title' => 'Lorem ipsum dolor sit amet, consetur adipiscing elit. Aliquam enim enim, pharetra in sodales at, interdum sit',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:51:40',
                'updated_at' => '2019-11-20 16:51:40',
                'seq_no' => 2,
                'link_url' => NULL,
            ),
            7 =>
            array(
                'id' => 8,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 4,
                'title' => 'Web Design',
                'sub_title' => 'Lorem ipsum dolor sit amet, consetur adipiscing elit. Aliquam enim enim, pharetra in sodales at, interdum sit',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:52:00',
                'updated_at' => '2019-11-20 16:52:00',
                'seq_no' => 3,
                'link_url' => NULL,
            ),
            8 =>
            array(
                'id' => 9,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 4,
                'title' => 'Web Design',
                'sub_title' => 'Lorem ipsum dolor sit amet, consetur adipiscing elit. Aliquam enim enim, pharetra in sodales at, interdum sit',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:52:23',
                'updated_at' => '2019-11-20 16:52:23',
                'seq_no' => 4,
                'link_url' => NULL,
            ),
            9 =>
            array(
                'id' => 10,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 4,
                'title' => 'Web Design',
                'sub_title' => 'Lorem ipsum dolor sit amet, consetur adipiscing elit. Aliquam enim enim, pharetra in sodales at, interdum sit',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:52:44',
                'updated_at' => '2019-11-20 16:52:44',
                'seq_no' => 5,
                'link_url' => NULL,
            ),
            10 =>
            array(
                'id' => 11,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 4,
                'title' => 'Web Design',
                'sub_title' => 'Lorem ipsum dolor sit amet, consetur adipiscing elit. Aliquam enim enim, pharetra in sodales at, interdum sit',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:53:14',
                'updated_at' => '2019-11-20 16:53:14',
                'seq_no' => 6,
                'link_url' => NULL,
            ),
            11 =>
            array(
                'id' => 12,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 5,
                'title' => 'Video Section',
                'sub_title' => 'See our latest promo video',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:55:13',
                'updated_at' => '2019-11-20 16:55:13',
                'seq_no' => 1,
                'link_url' => 'https://www.youtube.com/watch?v=YcCHmRBHw0c',
            ),
            12 =>
            array(
                'id' => 13,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 7,
                'title' => 'Ongoing projects',
                'sub_title' => '1200',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:57:06',
                'updated_at' => '2019-11-20 16:57:06',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            13 =>
            array(
                'id' => 14,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 7,
                'title' => 'Projects Done',
                'sub_title' => '100',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:57:52',
                'updated_at' => '2019-11-20 16:57:52',
                'seq_no' => 2,
                'link_url' => NULL,
            ),
            14 =>
            array(
                'id' => 15,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 7,
                'title' => 'Web Development',
                'sub_title' => '500',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:58:13',
                'updated_at' => '2019-11-20 16:58:13',
                'seq_no' => 3,
                'link_url' => NULL,
            ),
            15 =>
            array(
                'id' => 16,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 7,
                'title' => 'Country served',
                'sub_title' => '30',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 16:58:36',
                'updated_at' => '2019-11-20 16:58:36',
                'seq_no' => 4,
                'link_url' => NULL,
            ),
            16 =>
            array(
                'id' => 17,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 6,
                'title' => 'Our Digital Agency',
                'sub_title' => NULL,
                'highlight' => NULL,
                'content' => '<li>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</li>
<li>There are many variations of passages of Lorem Ipsum available</li>
<li>Simply dummy text of the printing and typesetting industry</li>
<li>It is a long established fact that a reader will be distracted by the readable</li>',
                'description' => '<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has standard dummy text ever since the 1500s, when an unknown printer took a galley of type. It was popularised in the 1960s with the release of Letraset sheets  Lorem Ipsum passages, and more recently with desktop software like Aldus Page of Lorem Ipsum.</p>',
                'short_description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has standard dummy text ever since the 1500s, when an unknown printer took a galley of type and type specimen book. It has survived not only five centuries, but also the leapinto electronic essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets Lorem Ipsum passages, and more recently with desktop publishing software like Aldus Pageof Lorem Ipsum.',
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:03:04',
                'updated_at' => '2019-11-20 17:03:04',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            17 =>
            array(
                'id' => 18,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 8,
                'title' => 'Our Brand Clients',
                'sub_title' => 'We work with wroldwide Company',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:05:42',
                'updated_at' => '2019-11-20 17:05:42',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            18 =>
            array(
                'id' => 19,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 8,
                'title' => 'Our Brand Clients',
                'sub_title' => 'We work with wroldwide Company',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:06:20',
                'updated_at' => '2019-11-20 17:06:20',
                'seq_no' => 2,
                'link_url' => NULL,
            ),
            19 =>
            array(
                'id' => 20,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 8,
                'title' => 'Our Brand Clients',
                'sub_title' => 'We work with wroldwide Company',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:06:46',
                'updated_at' => '2019-11-20 17:06:46',
                'seq_no' => 3,
                'link_url' => NULL,
            ),
            20 =>
            array(
                'id' => 21,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 8,
                'title' => 'Our Brand Clients',
                'sub_title' => 'We work with wroldwide Company',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:07:16',
                'updated_at' => '2019-11-20 17:07:16',
                'seq_no' => 4,
                'link_url' => NULL,
            ),
            21 =>
            array(
                'id' => 22,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 8,
                'title' => 'Our Brand Clients',
                'sub_title' => 'We work with wroldwide Company',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:08:14',
                'updated_at' => '2019-11-20 17:08:14',
                'seq_no' => 5,
                'link_url' => NULL,
            ),
            22 =>
            array(
                'id' => 23,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 8,
                'title' => 'Our Brand Clients',
                'sub_title' => 'We work with wroldwide Company',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:08:35',
                'updated_at' => '2019-11-20 17:08:35',
                'seq_no' => 6,
                'link_url' => NULL,
            ),
            23 =>
            array(
                'id' => 24,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 8,
                'title' => 'Our Brand Clients',
                'sub_title' => 'We work with wroldwide Company',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:09:29',
                'updated_at' => '2019-11-20 17:09:29',
                'seq_no' => 7,
                'link_url' => NULL,
            ),
            24 =>
            array(
                'id' => 25,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 8,
                'title' => 'Our Brand Clients',
                'sub_title' => 'We work with wroldwide Company',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:09:50',
                'updated_at' => '2019-11-20 17:09:50',
                'seq_no' => 8,
                'link_url' => NULL,
            ),
            25 =>
            array(
                'id' => 26,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 9,
                'title' => 'Services',
                'sub_title' => 'Why We Are Best  Choice?',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:13:38',
                'updated_at' => '2019-11-20 17:13:38',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            26 =>
            array(
                'id' => 27,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 17,
                'title' => 'About Us',
                'sub_title' => 'Why We Are  Best Choice?',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 17:50:20',
                'updated_at' => '2019-11-20 17:51:57',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            27 =>
            array(
                'id' => 28,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 18,
                'title' => 'John Smith',
                'sub_title' => 'User Interface Designer',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 19:37:51',
                'updated_at' => '2019-11-20 19:37:51',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            28 =>
            array(
                'id' => 29,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 18,
                'title' => 'John Deo',
                'sub_title' => 'SEO Specialist',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 19:38:25',
                'updated_at' => '2019-11-20 19:38:25',
                'seq_no' => 2,
                'link_url' => NULL,
            ),
            29 =>
            array(
                'id' => 30,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 18,
                'title' => 'Peter Parker',
                'sub_title' => 'Senior Web Developer',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 19:39:14',
                'updated_at' => '2019-11-20 19:39:14',
                'seq_no' => 3,
                'link_url' => NULL,
            ),
            30 =>
            array(
                'id' => 31,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 18,
                'title' => 'Jane Doe',
                'sub_title' => 'SEO Analyst/Specialist',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-20 19:39:55',
                'updated_at' => '2019-11-20 19:39:55',
                'seq_no' => 4,
                'link_url' => NULL,
            ),
            31 =>
            array(
                'id' => 32,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 12,
                'title' => 'Portfolio',
                'sub_title' => 'Why we are best choice?',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 12:20:27',
                'updated_at' => '2019-11-21 12:20:27',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            32 =>
            array(
                'id' => 33,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 14,
                'title' => 'Blog Page',
                'sub_title' => 'Why we are best choice?',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 12:28:01',
                'updated_at' => '2019-11-21 12:28:01',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            33 =>
            array(
                'id' => 34,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 31,
                'title' => '404 Page',
                'sub_title' => 'page not found?',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:43:42',
                'updated_at' => '2019-11-21 13:43:42',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            34 =>
            array(
                'id' => 35,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 32,
                'title' => '404',
                'sub_title' => 'Sorry not found page',
                'highlight' => 'Sorry the page you are looking for could not be found',
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:47:48',
                'updated_at' => '2019-11-21 13:47:48',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            35 =>
            array(
                'id' => 36,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 19,
                'title' => 'Career',
                'sub_title' => 'Career with our company',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:52:17',
                'updated_at' => '2019-11-21 13:52:17',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            36 =>
            array(
                'id' => 37,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 21,
                'title' => 'Price table',
                'sub_title' => 'Why We Are Best Choice?',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:56:17',
                'updated_at' => '2019-11-21 13:56:17',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            37 =>
            array(
                'id' => 38,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 24,
                'title' => 'Team Member',
                'sub_title' => 'Why We Are Best Choice?',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 13:59:13',
                'updated_at' => '2019-11-21 13:59:13',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            38 =>
            array(
                'id' => 39,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 27,
                'title' => 'Contact Us',
                'sub_title' => 'Stay connected with us',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-21 14:03:09',
                'updated_at' => '2019-11-21 14:03:09',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            39 =>
            array(
                'id' => 40,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 11,
                'title' => 'Testimonial',
                'sub_title' => 'Happy Clients Say?',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 17:54:45',
                'updated_at' => '2019-11-22 17:54:45',
                'seq_no' => 1,
                'link_url' => 'https://www.youtube.com/watch?v=dBlBYP1pQgE',
            ),
            40 =>
            array(
                'id' => 41,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 11,
                'title' => '-John Smith',
                'sub_title' => 'Creative Designer',
                'highlight' => '“ Nissimos ducimus qui blanditiis praesentium voluptatumatque corrupti quos dolores et quas molestias excepturi sint occaecati “',
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 17:56:03',
                'updated_at' => '2019-11-22 17:56:03',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            41 =>
            array(
                'id' => 42,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 11,
                'title' => '-Jane Doe',
                'sub_title' => 'SEO Specialist',
                'highlight' => '“ Nissimos ducimus qui blanditiis praesentium voluptatumatque corrupti quos dolores et quas molestias excepturi sint occaecati “',
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 17:56:40',
                'updated_at' => '2019-11-22 17:56:40',
                'seq_no' => 2,
                'link_url' => NULL,
            ),
            42 =>
            array(
                'id' => 43,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 10,
                'title' => 'Services',
                'sub_title' => NULL,
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 18:26:29',
                'updated_at' => '2019-11-22 19:00:32',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            43 =>
            array(
                'id' => 44,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 10,
                'title' => 'Responsive Design',
                'sub_title' => 'Lorem Ipsum is simply  dummy text of the printing and type setting industry lorem',
                'highlight' => 'flaticon-responsive',
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 18:27:16',
                'updated_at' => '2019-11-22 19:01:06',
                'seq_no' => 2,
                'link_url' => NULL,
            ),
            44 =>
            array(
                'id' => 45,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 10,
                'title' => 'Web Development',
                'sub_title' => 'Lorem Ipsum is simply  dummy text of the printing and type setting industry lorem',
                'highlight' => 'flaticon-coding',
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 18:27:38',
                'updated_at' => '2019-11-22 19:02:24',
                'seq_no' => 5,
                'link_url' => NULL,
            ),
            45 =>
            array(
                'id' => 46,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 10,
                'title' => 'Programming',
                'sub_title' => 'Lorem Ipsum is simply  dummy text of the printing and type setting industry lorem',
                'highlight' => 'flaticon-language',
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 18:27:57',
                'updated_at' => '2019-11-22 19:02:55',
                'seq_no' => 3,
                'link_url' => NULL,
            ),
            46 =>
            array(
                'id' => 47,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 10,
                'title' => 'Graphic Design',
                'sub_title' => 'Lorem Ipsum is simply  dummy text of the printing and type setting industry lorem',
                'highlight' => 'flaticon-vector-1',
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 18:28:15',
                'updated_at' => '2019-11-22 19:03:23',
                'seq_no' => 4,
                'link_url' => NULL,
            ),
            47 =>
            array(
                'id' => 48,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 20,
                'title' => 'Career image 1',
                'sub_title' => NULL,
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:12:37',
                'updated_at' => '2019-11-22 19:13:13',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            48 =>
            array(
                'id' => 49,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 20,
                'title' => 'career image 2',
                'sub_title' => NULL,
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:13:01',
                'updated_at' => '2019-11-22 19:13:22',
                'seq_no' => 2,
                'link_url' => NULL,
            ),
            49 =>
            array(
                'id' => 50,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 20,
                'title' => 'Interaction Designer',
                'sub_title' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:16:24',
                'updated_at' => '2019-11-22 19:16:24',
                'seq_no' => 3,
                'link_url' => NULL,
            ),
            50 =>
            array(
                'id' => 51,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 20,
                'title' => 'Web Developer',
                'sub_title' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:18:30',
                'updated_at' => '2019-11-22 19:18:30',
                'seq_no' => 4,
                'link_url' => NULL,
            ),
            51 =>
            array(
                'id' => 52,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 20,
                'title' => 'Software Engineer',
                'sub_title' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:18:48',
                'updated_at' => '2019-11-22 19:18:48',
                'seq_no' => 5,
                'link_url' => NULL,
            ),
            52 =>
            array(
                'id' => 53,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 20,
                'title' => 'Game Developer',
                'sub_title' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:19:09',
                'updated_at' => '2019-11-22 19:19:09',
                'seq_no' => 6,
                'link_url' => NULL,
            ),
            53 =>
            array(
                'id' => 54,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 33,
                'title' => 'John Smith',
                'sub_title' => 'UX Designer',
                'highlight' => NULL,
                'content' => '<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publiLorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
<p>Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing.</p>',
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:27:06',
                'updated_at' => '2019-11-22 19:28:16',
                'seq_no' => NULL,
                'link_url' => NULL,
            ),
            54 =>
            array(
                'id' => 55,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 25,
                'title' => 'Adobe Photoshop',
                'sub_title' => '90',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:56:14',
                'updated_at' => '2019-11-22 19:56:15',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
            55 =>
            array(
                'id' => 56,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 25,
                'title' => 'Adobe Indesign',
                'sub_title' => '88',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:56:49',
                'updated_at' => '2019-11-22 19:56:49',
                'seq_no' => 2,
                'link_url' => NULL,
            ),
            56 =>
            array(
                'id' => 57,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 25,
                'title' => 'Adobe Flash',
                'sub_title' => '80',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:57:05',
                'updated_at' => '2019-11-22 19:57:05',
                'seq_no' => 3,
                'link_url' => NULL,
            ),
            57 =>
            array(
                'id' => 58,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 25,
                'title' => 'Adobe After Effect',
                'sub_title' => '85',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:57:25',
                'updated_at' => '2019-11-22 19:57:25',
                'seq_no' => 4,
                'link_url' => NULL,
            ),
            58 =>
            array(
                'id' => 59,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 25,
                'title' => 'Adobe Dreamweaver',
                'sub_title' => '95',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:57:50',
                'updated_at' => '2019-11-22 19:57:50',
                'seq_no' => 5,
                'link_url' => NULL,
            ),
            59 =>
            array(
                'id' => 60,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 25,
                'title' => 'Adobe Illustrator',
                'sub_title' => '75',
                'highlight' => NULL,
                'content' => NULL,
                'description' => NULL,
                'short_description' => NULL,
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 19:58:42',
                'updated_at' => '2019-11-22 19:58:42',
                'seq_no' => 6,
                'link_url' => NULL,
            ),
            60 =>
            array(
                'id' => 61,
                'type' => NULL,
                'page_id' => NULL,
                'component_id' => 26,
                'title' => 'Why We Are Best Choice?',
                'sub_title' => NULL,
                'highlight' => NULL,
                'content' => '<div class="panel tab-acc-panel">
<div class="tab-acc-panel-heading" role="tab" id="headingOne">
<h5 class="tab-acc-panel-title">
<a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
Where does it come from? <span class="acc_toggle_icon"></span>
</a>
</h5>
</div>
<div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
<div class="tab-acc-body">
<p>Contrary to belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College</p>
</div>
</div>
</div>
<div class="panel tab-acc-panel">
<div class="tab-acc-panel-heading" role="tab" id="headingTwo">
<h5 class="tab-acc-panel-title">
<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
Where can I get some demo text ? <span class="acc_toggle_icon"></span>
</a>
</h5>
</div>
<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
<div class="tab-acc-body">
<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor</p>
</div>
</div>
</div>
<div class="panel tab-acc-panel">
<div class="tab-acc-panel-heading" role="tab" id="headingThree">
<h5 class="tab-acc-panel-title">
<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
What is Lorem Ipsum? <span class="acc_toggle_icon"></span>
</a>
</h5>
</div>
<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
<div class="tab-acc-body">
<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College</p>
</div>
</div>
</div>',
                'description' => NULL,
                'short_description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.',
                'post_image' => NULL,
                'likes' => NULL,
                'comments' => NULL,
                'category' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-22 20:05:19',
                'updated_at' => '2019-11-22 20:07:44',
                'seq_no' => 1,
                'link_url' => NULL,
            ),
        ));
    }
}
