<?php

use Illuminate\Database\Seeder;

class DefaultCompaniesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('default_companies')->delete();
        
        \DB::table('default_companies')->insert(array (
            0 => 
            array (
                'id' => 1,
                'property' => 'industry',
                'value' => 'transport',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => 2,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-26 14:11:09',
                'updated_at' => '2019-12-24 00:45:40',
            ),
            1 => 
            array (
                'id' => 2,
                'property' => 'ownership',
                'value' => 'llc',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => 2,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-26 14:11:53',
                'updated_at' => '2019-12-24 00:45:31',
            ),
            2 => 
            array (
                'id' => 3,
                'property' => 'employees',
                'value' => '20',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-26 14:13:26',
                'updated_at' => '2019-09-26 14:13:26',
            ),
            3 => 
            array (
                'id' => 4,
                'property' => 'est_date',
                'value' => '09-20-2019',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-26 14:13:48',
                'updated_at' => '2019-09-26 14:13:48',
            ),
            4 => 
            array (
                'id' => 5,
                'property' => 'phone_number',
                'value' => '5122981111',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => 2,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-26 14:14:24',
                'updated_at' => '2020-01-04 19:35:52',
            ),
            5 => 
            array (
                'id' => 6,
                'property' => 'email',
                'value' => 'order@cratesonskates.com',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-26 14:15:21',
                'updated_at' => '2019-12-24 00:14:13',
            ),
            6 => 
            array (
                'id' => 7,
                'property' => 'description',
                'value' => 'Austin Co-Owner Lauren Doering has moved eight times in her life, and every time has been within the Austin Metro Area. She and her partners decided to launch Crates on Skates in the growing city of Austin, TX. They bring environmentally friendly moving crates to the central Texas market. Crates on Skates are a more convenient, cost effective and stronger alternative to cardboard. Moving companies really like them too.',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-26 14:16:22',
                'updated_at' => '2019-12-24 00:17:03',
            ),
            7 => 
            array (
                'id' => 11,
                'property' => 'country',
                'value' => 'USA',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-26 14:18:42',
                'updated_at' => '2019-12-24 00:23:35',
            ),
            8 => 
            array (
                'id' => 22,
                'property' => 'website',
                'value' => 'cratesonskates.com',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 14:58:21',
                'updated_at' => '2019-12-24 00:19:02',
            ),
            9 => 
            array (
                'id' => 24,
                'property' => 'tax number',
                'value' => '234234234234',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:00:06',
                'updated_at' => '2019-09-27 18:00:06',
            ),
            10 => 
            array (
                'id' => 26,
                'property' => 'reservation_email_order',
                'value' => 'rak3sh.shrestha@gmail.com',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 16:43:51',
                'updated_at' => '2019-12-23 16:43:51',
            ),
            11 => 
            array (
                'id' => 27,
                'property' => 'send_reservation_sms',
                'value' => 'false',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 16:44:14',
                'updated_at' => '2019-12-23 16:44:14',
            ),
            12 => 
            array (
                'id' => 28,
                'property' => 'sms_auth_token',
                'value' => '34298a20a517a05b92dedc4c56a43c40',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 16:47:47',
                'updated_at' => '2019-12-23 16:47:47',
            ),
            13 => 
            array (
                'id' => 29,
                'property' => 'sms_sid',
                'value' => 'AC8f83c13ba147daf3f6900c9fc020e3a1',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 16:48:04',
                'updated_at' => '2019-12-23 16:48:04',
            ),
            14 => 
            array (
                'id' => 30,
                'property' => 'default_phone_code',
                'value' => '1',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 16:48:35',
                'updated_at' => '2019-12-23 16:48:35',
            ),
            15 => 
            array (
                'id' => 31,
                'property' => 'sms_phone_number',
                'value' => '18602007140',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 16:48:47',
                'updated_at' => '2019-12-23 16:48:47',
            ),
            16 => 
            array (
                'id' => 32,
                'property' => 'sms_reservation_phone',
                'value' => '8609869303',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 21:25:10',
                'updated_at' => '2019-12-23 22:20:07',
            ),
            17 => 
            array (
                'id' => 33,
                'property' => 'icon_sidebar',
                'value' => '93ef31285421bb9ba65b5cc2031f540f.png',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 22:20:31',
                'updated_at' => '2019-12-24 02:36:36',
            ),
            18 => 
            array (
                'id' => 34,
                'property' => 'icon_login',
                'value' => 'bed8a7bc7bd275e77f7a2782742db3a0.png',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 22:21:50',
                'updated_at' => '2019-12-24 02:36:54',
            ),
            19 => 
            array (
                'id' => 35,
                'property' => 'icon_favicon',
                'value' => '4b36c1e45e979f85ea0ddba362096106.png',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 22:22:54',
                'updated_at' => '2019-12-24 02:20:58',
            ),
            20 => 
            array (
                'id' => 39,
                'property' => 'address',
                'value' => '404 W. Powell Lane | #203 | Austin, TX - 78753',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-24 01:09:03',
                'updated_at' => '2019-12-24 01:09:03',
            ),
            21 => 
            array (
                'id' => 40,
                'property' => 'company_name',
                'value' => 'Crates on Skates',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-24 01:19:29',
                'updated_at' => '2019-12-24 01:19:29',
            ),
            22 => 
            array (
                'id' => 41,
                'property' => 'facebook',
                'value' => 'https://www.facebook.com',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-04 19:36:23',
                'updated_at' => '2020-01-04 19:36:23',
            ),
            23 => 
            array (
                'id' => 42,
                'property' => 'google_plus',
                'value' => 'https://aboutme.google.com',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-04 20:05:45',
                'updated_at' => '2020-01-04 20:05:45',
            ),
            24 => 
            array (
                'id' => 43,
                'property' => 'yelp',
                'value' => 'https://www.yelp.com',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-04 20:06:07',
                'updated_at' => '2020-01-04 20:06:07',
            ),
            25 => 
            array (
                'id' => 44,
                'property' => 'instagram',
                'value' => 'https://www.instagram.com',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-04 20:06:28',
                'updated_at' => '2020-01-04 20:06:28',
            ),
            26 => 
            array (
                'id' => 45,
                'property' => 'youtube',
                'value' => 'https://www.youtube.com',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-04 20:06:47',
                'updated_at' => '2020-01-04 20:06:47',
            ),
            27 => 
            array (
                'id' => 46,
                'property' => 'hero_video',
                'value' => 'https://www.youtube.com/embed/jz8tIbanOWk',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-04 20:12:57',
                'updated_at' => '2020-01-04 20:24:28',
            ),
            28 => 
            array (
                'id' => 47,
                'property' => 'minimum_cart_amount',
                'value' => '6',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-09 20:23:40',
                'updated_at' => '2020-01-10 16:44:37',
            ),
            29 => 
            array (
                'id' => 48,
                'property' => 'enquire_email',
                'value' => 'cratesEnquire@gmail.com',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-09 20:29:06',
                'updated_at' => '2020-01-09 20:29:06',
            ),
            30 => 
            array (
                'id' => 49,
                'property' => 'authorize_net_name',
                'value' => '76hXyvLm27',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-13 19:11:54',
                'updated_at' => '2020-01-17 18:24:24',
            ),
            31 => 
            array (
                'id' => 50,
                'property' => 'authorize_net_transaction_key',
                'value' => '3DH5xUD333F3kb34',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-13 19:12:13',
                'updated_at' => '2020-01-17 18:24:18',
            ),
            32 => 
            array (
                'id' => 51,
                'property' => 'minimum_reservations_days',
                'value' => '2',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-14 13:54:05',
                'updated_at' => '2020-01-14 13:54:05',
            ),
            33 => 
            array (
                'id' => 53,
                'property' => 'sales_tax',
                'value' => '10',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 18:26:15',
                'updated_at' => '2020-01-17 18:26:15',
            ),
        ));
        
        
    }
}