<?php

use Illuminate\Database\Seeder;

class FaqsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        \DB::statement('set foreign_key_checks = 0');
        \DB::table('faqs')->delete();
        \DB::statement('set foreign_key_checks = 1');
        
        \DB::table('faqs')->insert(array (
            0 => 
            array (
                'id' => 9,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'Is Crates On Skates A Moving Company?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:24:58',
                'updated_at' => '2020-01-17 17:59:20',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 1,
            ),
            1 => 
            array (
                'id' => 10,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'Do I Need To Be Home During The Delivery And Pickup Of My Crates?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:32:38',
                'updated_at' => '2020-01-17 17:32:38',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 2,
            ),
            2 => 
            array (
                'id' => 11,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'Does The Crates On Skates Rental Cover Both Delivery And Pickup?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:33:24',
                'updated_at' => '2020-01-17 17:33:24',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 3,
            ),
            3 => 
            array (
                'id' => 12,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'How Does Crates On Skates Deliver And Pick Up The Crates?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:33:56',
                'updated_at' => '2020-01-17 17:33:56',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 4,
            ),
            4 => 
            array (
                'id' => 13,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'How Do I Pay?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:34:34',
                'updated_at' => '2020-01-17 17:34:34',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 5,
            ),
            5 => 
            array (
                'id' => 14,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'Will I Receive A Call From Crates On Skates Prior To My Deliver And Pickup?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:34:57',
                'updated_at' => '2020-01-17 17:34:57',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 6,
            ),
            6 => 
            array (
                'id' => 15,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'Can I Keep My Crates Longer If I Need To?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:35:23',
                'updated_at' => '2020-01-17 17:35:23',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 7,
            ),
            7 => 
            array (
                'id' => 16,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'What If I Need More Crates?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:35:47',
                'updated_at' => '2020-01-17 17:35:47',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 8,
            ),
            8 => 
            array (
                'id' => 17,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'Are The Crates Cleaned Between Rentals?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:36:14',
                'updated_at' => '2020-01-17 17:36:14',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 9,
            ),
            9 => 
            array (
                'id' => 18,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'Does Crates On Skates Deliver To Walkup Units?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:36:34',
                'updated_at' => '2020-01-17 17:36:34',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 10,
            ),
            10 => 
            array (
                'id' => 19,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'Does Crates On Skates Service Long Distance Or Out Of Area Moves?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:36:56',
                'updated_at' => '2020-01-17 17:36:56',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 11,
            ),
            11 => 
            array (
                'id' => 20,
                'table' => NULL,
                'table_id' => NULL,
                'section' => NULL,
                'question' => 'What Are Crates On Skates Wardrobes?',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 17:37:14',
                'updated_at' => '2020-01-17 17:37:14',
                'is_faq' => 1,
                'is_approved' => 0,
                'parent_id' => NULL,
                'seq' => 12,
            ),
        ));
        
        
    }
}