<?php

use Illuminate\Database\Seeder;

class IconsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('icons')->delete();
        
        \DB::table('icons')->insert(array (
            0 => 
            array (
                'id' => 7,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Menu icon',
                'icon_class' => 'fas fa-bars',
                'is_active' => 0,
                'is_deleted' => 1,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => 10,
                'deleted_at' => '2019-09-27 18:13:18',
                'created_at' => '2019-09-27 18:12:28',
                'updated_at' => '2019-09-27 18:13:18',
            ),
            1 => 
            array (
                'id' => 8,
                'icon_group' => 'fontawesome',
                'icon_name' => 'menu',
                'icon_class' => 'fas fa-bars',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:18:28',
                'updated_at' => '2019-09-27 18:28:10',
            ),
            2 => 
            array (
                'id' => 9,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Role and Permission',
                'icon_class' => 'fas fa-user-tag',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:33:56',
                'updated_at' => '2019-09-27 18:33:56',
            ),
            3 => 
            array (
                'id' => 10,
                'icon_group' => 'Flaticon',
                'icon_name' => 'Site Settings',
                'icon_class' => 'flaticon2-settings',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:36:39',
                'updated_at' => '2019-09-27 18:38:14',
            ),
            4 => 
            array (
                'id' => 11,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Audit',
                'icon_class' => 'fas fa-user-md',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:39:57',
                'updated_at' => '2019-09-27 18:39:57',
            ),
            5 => 
            array (
                'id' => 12,
                'icon_group' => 'fontawesome',
                'icon_name' => 'Default Company',
                'icon_class' => 'far fa-building',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:41:21',
                'updated_at' => '2019-09-27 18:41:21',
            ),
            6 => 
            array (
                'id' => 13,
                'icon_group' => 'fontawesome',
                'icon_name' => 'Users Control',
                'icon_class' => 'fas fa-users-cog',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:42:37',
                'updated_at' => '2019-09-27 18:42:37',
            ),
            7 => 
            array (
                'id' => 14,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Note',
                'icon_class' => 'fas flaticon-list',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:44:17',
                'updated_at' => '2019-09-27 18:44:17',
            ),
            8 => 
            array (
                'id' => 15,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Lookups',
                'icon_class' => 'fas fa-search',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:46:37',
                'updated_at' => '2019-09-27 18:46:37',
            ),
            9 => 
            array (
                'id' => 16,
                'icon_group' => 'Flaticon',
                'icon_name' => 'Validation',
                'icon_class' => 'flaticon2-list-1',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:47:53',
                'updated_at' => '2019-09-27 18:47:53',
            ),
            10 => 
            array (
                'id' => 17,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'User Logs',
                'icon_class' => 'fas fa-user-clock',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:49:13',
                'updated_at' => '2019-09-27 18:49:13',
            ),
            11 => 
            array (
                'id' => 18,
                'icon_group' => 'Flaticon',
                'icon_name' => 'base',
                'icon_class' => 'flaticon2-rocket-2',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 18:50:20',
                'updated_at' => '2019-10-03 12:43:05',
            ),
            12 => 
            array (
                'id' => 19,
                'icon_group' => 'flaticon',
                'icon_name' => 'Icon',
                'icon_class' => 'fas fa-icons',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 19:35:21',
                'updated_at' => '2019-09-30 20:12:11',
            ),
            13 => 
            array (
                'id' => 20,
                'icon_group' => 'flaticon',
                'icon_name' => 'templates',
                'icon_class' => 'flaticon2-drop',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-24 12:16:38',
                'updated_at' => '2019-10-24 12:16:38',
            ),
            14 => 
            array (
                'id' => 21,
                'icon_group' => 'fontawesome',
                'icon_name' => 'blog',
                'icon_class' => 'fa fa-blog',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-24 12:40:30',
                'updated_at' => '2019-12-31 00:36:34',
            ),
            15 => 
            array (
                'id' => 22,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Clients',
                'icon_class' => 'fa fa-user-tie',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-26 14:08:59',
                'updated_at' => '2019-12-09 19:08:47',
            ),
            16 => 
            array (
                'id' => 23,
                'icon_group' => 'Flaticon',
                'icon_name' => 'Members',
                'icon_class' => 'flaticon2-group',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-26 18:44:29',
                'updated_at' => '2019-11-26 18:50:35',
            ),
            17 => 
            array (
                'id' => 24,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Account',
                'icon_class' => 'fas fa-user',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-11-29 20:24:23',
                'updated_at' => '2019-11-29 20:24:23',
            ),
            18 => 
            array (
                'id' => 25,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Order',
                'icon_class' => 'fa fa-store',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-02 19:14:26',
                'updated_at' => '2019-12-31 00:37:23',
            ),
            19 => 
            array (
                'id' => 26,
                'icon_group' => 'fontawesome',
                'icon_name' => 'inventory',
                'icon_class' => 'fas fa-dolly-flatbed',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-02 19:21:52',
                'updated_at' => '2019-12-02 19:21:52',
            ),
            20 => 
            array (
                'id' => 27,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Address',
                'icon_class' => 'far fa-address-card',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-02 19:54:35',
                'updated_at' => '2019-12-02 19:54:35',
            ),
            21 => 
            array (
                'id' => 28,
                'icon_group' => 'Flaticon',
                'icon_name' => 'admin',
                'icon_class' => 'flaticon-dashboard',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-09 18:34:17',
                'updated_at' => '2019-12-16 18:18:59',
            ),
            22 => 
            array (
                'id' => 29,
                'icon_group' => 'Flaticon',
                'icon_name' => 'orders',
                'icon_class' => 'flaticon-list',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-09 18:44:38',
                'updated_at' => '2019-12-09 18:44:38',
            ),
            23 => 
            array (
                'id' => 30,
                'icon_group' => 'flaticon',
                'icon_name' => 'product',
                'icon_class' => 'flaticon2-gift-1',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-09 18:57:54',
                'updated_at' => '2019-12-09 19:10:42',
            ),
            24 => 
            array (
                'id' => 31,
                'icon_group' => 'flaticon',
                'icon_name' => 'accounts',
                'icon_class' => 'flaticon-users',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-09 19:11:39',
                'updated_at' => '2019-12-09 19:14:16',
            ),
            25 => 
            array (
                'id' => 32,
                'icon_group' => 'flaticon',
                'icon_name' => 'Reports',
                'icon_class' => 'flaticon2-crisp-icons',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-09 19:15:30',
                'updated_at' => '2019-12-09 19:15:30',
            ),
            26 => 
            array (
                'id' => 33,
                'icon_group' => 'Flaticon',
                'icon_name' => 'User Control',
                'icon_class' => 'flaticon2-user-1',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-11 19:18:09',
                'updated_at' => '2019-12-11 19:18:09',
            ),
            27 => 
            array (
                'id' => 34,
                'icon_group' => 'Flaticon',
                'icon_name' => 'site setting',
                'icon_class' => 'flaticon-cogwheel',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-11 19:19:09',
                'updated_at' => '2019-12-11 19:19:19',
            ),
            28 => 
            array (
                'id' => 35,
                'icon_group' => 'lineawesome',
                'icon_name' => 'zip',
                'icon_class' => 'la la-file-zip-o',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-16 20:29:32',
                'updated_at' => '2019-12-16 20:29:52',
            ),
            29 => 
            array (
                'id' => 36,
                'icon_group' => 'lineawesome',
                'icon_name' => 'coupon',
                'icon_class' => 'la la-barcode',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-16 20:31:08',
                'updated_at' => '2019-12-16 20:31:08',
            ),
            30 => 
            array (
                'id' => 37,
                'icon_group' => 'Lineawesome',
                'icon_name' => 'payment',
                'icon_class' => 'la la-money',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-16 20:32:53',
                'updated_at' => '2019-12-16 20:32:53',
            ),
            31 => 
            array (
                'id' => 38,
                'icon_group' => 'Lineawesome',
                'icon_name' => 'Content',
                'icon_class' => 'la la-copy',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-16 20:34:05',
                'updated_at' => '2019-12-16 20:34:05',
            ),
            32 => 
            array (
                'id' => 39,
                'icon_group' => 'socicons',
                'icon_name' => 'inventories',
                'icon_class' => 'socicon-buffer',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-16 20:39:10',
                'updated_at' => '2019-12-16 20:39:10',
            ),
            33 => 
            array (
                'id' => 40,
                'icon_group' => 'flaticon',
                'icon_name' => 'package',
                'icon_class' => 'flaticon2-gift-1',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-16 20:39:10',
                'updated_at' => '2019-12-16 20:39:10',
            ),
            34 => 
            array (
                'id' => 43,
                'icon_group' => 'flaticon',
                'icon_name' => 'Purchase Order',
                'icon_class' => 'flaticon2-delivery-package',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 15:01:07',
                'updated_at' => '2019-12-23 15:01:07',
            ),
            35 => 
            array (
                'id' => 44,
                'icon_group' => 'flaticon',
                'icon_name' => 'Quotes',
                'icon_class' => 'flaticon-notepad',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 15:02:00',
                'updated_at' => '2019-12-23 15:02:00',
            ),
            36 => 
            array (
                'id' => 45,
                'icon_group' => 'Lineawesome',
                'icon_name' => 'Email Templates',
                'icon_class' => 'la la-envelope',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-16 20:34:05',
                'updated_at' => '2019-12-16 20:34:05',
            ),
            37 => 
            array (
                'id' => 46,
                'icon_group' => 'Fontawesome',
                'icon_name' => 'Dashboard',
                'icon_class' => 'fas fa-tachometer-alt',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-31 11:31:34',
                'updated_at' => '2019-12-31 11:33:07',
            ),
            38 => 
            array (
                'id' => 47,
                'icon_group' => 'flaticon',
                'icon_name' => 'Calendar',
                'icon_class' => 'flaticon-event-calendar-symbol',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-31 12:26:26',
                'updated_at' => '2019-12-31 12:34:08',
            ),
            39 => 
            array (
                'id' => 48,
                'icon_group' => 'flaticon',
                'icon_name' => 'Account Heads',
                'icon_class' => 'flaticon-profile-1',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-01 16:32:29',
                'updated_at' => '2020-01-01 16:32:29',
            ),
            40 => 
            array (
                'id' => 49,
                'icon_group' => 'fontawesome',
                'icon_name' => 'bills',
                'icon_class' => 'fa fa-file-invoice-dollar',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-01 16:41:30',
                'updated_at' => '2020-01-01 16:41:30',
            ),
            41 => 
            array (
                'id' => 52,
                'icon_group' => 'lineawesone',
                'icon_name' => 'Bank Master',
                'icon_class' => 'la la-bank',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-03 13:31:13',
                'updated_at' => '2020-01-03 13:31:13',
            ),
            42 => 
            array (
                'id' => 53,
                'icon_group' => 'fontawesome',
                'icon_name' => 'Cash Master',
                'icon_class' => 'fa fa-dollar-sign',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-03 13:32:14',
                'updated_at' => '2020-01-03 13:32:14',
            ),
            43 => 
            array (
                'id' => 54,
                'icon_group' => 'fontawesome',
                'icon_name' => 'Contact',
                'icon_class' => 'fa fa-id-badge',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-08 17:20:31',
                'updated_at' => '2020-01-09 17:31:27',
            ),
            44 => 
            array (
                'id' => 56,
                'icon_group' => 'flaticon',
                'icon_name' => 'Journal',
                'icon_class' => 'flaticon-interface-4',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-15 18:56:14',
                'updated_at' => '2020-01-15 18:56:14',
            ),
            45 => 
            array (
                'id' => 58,
                'icon_group' => 'fontawesome',
                'icon_name' => 'faq',
                'icon_class' => 'far fa-question-circle',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-17 18:51:19',
                'updated_at' => '2020-01-17 18:51:19',
            ),
        ));
        
        
    }
}