<?php

use Illuminate\Database\Seeder;

class PackagePriceItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        \DB::statement('set foreign_key_checks = 0');
        \DB::table('package_price_items')->delete();
        \DB::statement('set foreign_key_checks = 1');
        \DB::table('package_price_items')->insert(array (
            0 => 
            array (
                'created_at' => '2019-12-31 20:47:02',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 1,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 1,
                'quantity' => 24,
                'updated_at' => '2019-12-31 20:47:02',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            1 => 
            array (
                'created_at' => '2019-12-31 20:47:02',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 2,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 1,
                'quantity' => 2,
                'updated_at' => '2019-12-31 20:47:02',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            2 => 
            array (
                'created_at' => '2019-12-31 20:47:02',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 3,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 1,
                'quantity' => 3,
                'updated_at' => '2019-12-31 20:47:02',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            3 => 
            array (
                'created_at' => '2019-12-31 20:47:02',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 4,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 1,
                'quantity' => 26,
                'updated_at' => '2019-12-31 20:47:02',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            4 => 
            array (
                'created_at' => '2019-12-31 20:48:48',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 5,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 2,
                'quantity' => 32,
                'updated_at' => '2019-12-31 20:48:48',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            5 => 
            array (
                'created_at' => '2019-12-31 20:48:48',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 6,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 2,
                'quantity' => 4,
                'updated_at' => '2019-12-31 20:48:48',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            6 => 
            array (
                'created_at' => '2019-12-31 20:48:48',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 7,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 2,
                'quantity' => 4,
                'updated_at' => '2019-12-31 20:48:48',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            7 => 
            array (
                'created_at' => '2019-12-31 20:48:48',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 8,
                'inv_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 2,
                'quantity' => 1,
                'updated_at' => '2019-12-31 20:48:48',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            8 => 
            array (
                'created_at' => '2019-12-31 20:48:48',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 9,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 2,
                'quantity' => 36,
                'updated_at' => '2019-12-31 20:48:48',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            9 => 
            array (
                'created_at' => '2019-12-31 20:49:38',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 10,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 3,
                'quantity' => 48,
                'updated_at' => '2019-12-31 20:49:38',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            10 => 
            array (
                'created_at' => '2019-12-31 20:49:38',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 11,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 3,
                'quantity' => 6,
                'updated_at' => '2019-12-31 20:49:38',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            11 => 
            array (
                'created_at' => '2019-12-31 20:49:38',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 12,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 3,
                'quantity' => 6,
                'updated_at' => '2019-12-31 20:49:38',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            12 => 
            array (
                'created_at' => '2019-12-31 20:49:38',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 13,
                'inv_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 3,
                'quantity' => 1,
                'updated_at' => '2019-12-31 20:49:38',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            13 => 
            array (
                'created_at' => '2019-12-31 20:49:38',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 14,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 3,
                'quantity' => 54,
                'updated_at' => '2019-12-31 20:49:38',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            14 => 
            array (
                'created_at' => '2019-12-31 20:50:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 15,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 4,
                'quantity' => 64,
                'updated_at' => '2019-12-31 20:50:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            15 => 
            array (
                'created_at' => '2019-12-31 20:50:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 16,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 4,
                'quantity' => 8,
                'updated_at' => '2019-12-31 20:50:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            16 => 
            array (
                'created_at' => '2019-12-31 20:50:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 17,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 4,
                'quantity' => 8,
                'updated_at' => '2019-12-31 20:50:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            17 => 
            array (
                'created_at' => '2019-12-31 20:50:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 18,
                'inv_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 4,
                'quantity' => 1,
                'updated_at' => '2019-12-31 20:50:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            18 => 
            array (
                'created_at' => '2019-12-31 20:50:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 19,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 4,
                'quantity' => 72,
                'updated_at' => '2019-12-31 20:50:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            19 => 
            array (
                'created_at' => '2019-12-31 20:51:12',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 20,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 5,
                'quantity' => 80,
                'updated_at' => '2019-12-31 20:51:12',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            20 => 
            array (
                'created_at' => '2019-12-31 20:51:12',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 21,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 5,
                'quantity' => 10,
                'updated_at' => '2019-12-31 20:51:12',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            21 => 
            array (
                'created_at' => '2019-12-31 20:51:12',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 22,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 5,
                'quantity' => 10,
                'updated_at' => '2019-12-31 20:51:12',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            22 => 
            array (
                'created_at' => '2019-12-31 20:51:12',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 23,
                'inv_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 5,
                'quantity' => 2,
                'updated_at' => '2019-12-31 20:51:12',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            23 => 
            array (
                'created_at' => '2019-12-31 20:51:12',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 24,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 5,
                'quantity' => 90,
                'updated_at' => '2019-12-31 20:51:12',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            24 => 
            array (
                'created_at' => '2019-12-31 20:51:51',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 25,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 6,
                'quantity' => 120,
                'updated_at' => '2019-12-31 20:51:51',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            25 => 
            array (
                'created_at' => '2019-12-31 20:51:51',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 26,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 6,
                'quantity' => 12,
                'updated_at' => '2019-12-31 20:51:51',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            26 => 
            array (
                'created_at' => '2019-12-31 20:51:51',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 27,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 6,
                'quantity' => 15,
                'updated_at' => '2019-12-31 20:51:51',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            27 => 
            array (
                'created_at' => '2019-12-31 20:51:51',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 28,
                'inv_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 6,
                'quantity' => 2,
                'updated_at' => '2019-12-31 20:51:51',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            28 => 
            array (
                'created_at' => '2019-12-31 20:51:51',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 29,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 6,
                'quantity' => 132,
                'updated_at' => '2019-12-31 20:51:51',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            29 => 
            array (
                'created_at' => '2019-12-31 20:52:54',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 30,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 7,
                'quantity' => 50,
                'updated_at' => '2019-12-31 20:52:54',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            30 => 
            array (
                'created_at' => '2019-12-31 20:52:54',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 31,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 7,
                'quantity' => 5,
                'updated_at' => '2019-12-31 20:52:54',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            31 => 
            array (
                'created_at' => '2019-12-31 20:52:54',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 32,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 7,
                'quantity' => 5,
                'updated_at' => '2019-12-31 20:52:54',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            32 => 
            array (
                'created_at' => '2019-12-31 20:52:54',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 33,
                'inv_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 7,
                'quantity' => 1,
                'updated_at' => '2019-12-31 20:52:54',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            33 => 
            array (
                'created_at' => '2019-12-31 20:52:54',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 34,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 7,
                'quantity' => 56,
                'updated_at' => '2019-12-31 20:52:54',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            34 => 
            array (
                'created_at' => '2019-12-31 20:53:36',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 35,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 8,
                'quantity' => 100,
                'updated_at' => '2019-12-31 20:53:36',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            35 => 
            array (
                'created_at' => '2019-12-31 20:53:36',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 36,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 8,
                'quantity' => 10,
                'updated_at' => '2019-12-31 20:53:36',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            36 => 
            array (
                'created_at' => '2019-12-31 20:53:36',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 37,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 8,
                'quantity' => 10,
                'updated_at' => '2019-12-31 20:53:36',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            37 => 
            array (
                'created_at' => '2019-12-31 20:53:36',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 38,
                'inv_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 8,
                'quantity' => 2,
                'updated_at' => '2019-12-31 20:53:36',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            38 => 
            array (
                'created_at' => '2019-12-31 20:53:36',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 39,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 8,
                'quantity' => 110,
                'updated_at' => '2019-12-31 20:53:36',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            39 => 
            array (
                'created_at' => '2019-12-31 20:54:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 40,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 9,
                'quantity' => 150,
                'updated_at' => '2019-12-31 20:54:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            40 => 
            array (
                'created_at' => '2019-12-31 20:54:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 41,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 9,
                'quantity' => 15,
                'updated_at' => '2019-12-31 20:54:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            41 => 
            array (
                'created_at' => '2019-12-31 20:54:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 42,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 9,
                'quantity' => 15,
                'updated_at' => '2019-12-31 20:54:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            42 => 
            array (
                'created_at' => '2019-12-31 20:54:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 43,
                'inv_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 9,
                'quantity' => 3,
                'updated_at' => '2019-12-31 20:54:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            43 => 
            array (
                'created_at' => '2019-12-31 20:54:29',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 44,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 9,
                'quantity' => 165,
                'updated_at' => '2019-12-31 20:54:29',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            44 => 
            array (
                'created_at' => '2019-12-31 20:55:16',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 45,
                'inv_id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 10,
                'quantity' => 200,
                'updated_at' => '2019-12-31 20:55:16',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            45 => 
            array (
                'created_at' => '2019-12-31 20:55:16',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 46,
                'inv_id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 10,
                'quantity' => 20,
                'updated_at' => '2019-12-31 20:55:16',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            46 => 
            array (
                'created_at' => '2019-12-31 20:55:16',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 47,
                'inv_id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 10,
                'quantity' => 20,
                'updated_at' => '2019-12-31 20:55:16',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            47 => 
            array (
                'created_at' => '2019-12-31 20:55:16',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 48,
                'inv_id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 10,
                'quantity' => 4,
                'updated_at' => '2019-12-31 20:55:16',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
            48 => 
            array (
                'created_at' => '2019-12-31 20:55:16',
                'deleted_at' => NULL,
                'dis_amt' => 0.0,
                'dis_rate' => NULL,
                'dis_type' => 'flat',
                'id' => 49,
                'inv_id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'package_price_id' => 10,
                'quantity' => 220,
                'updated_at' => '2019-12-31 20:55:16',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
            ),
        ));
        
        
    }
}