<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        \DB::statement('set foreign_key_checks = 0');
        \DB::table('products')->delete();
        \DB::statement('set foreign_key_checks = 1');
        \DB::table('products')->insert(array (
            0 => 
            array (
                'brand_id' => 1,
                'code' => 'lc',
                'created_at' => '2019-12-31 20:07:22',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:07:37',
                'name' => 'Large Crate',
                'short_desc' => 'Large Crate',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '2',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:07:37',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            1 => 
            array (
                'brand_id' => 1,
                'code' => 'xlc',
                'created_at' => '2019-12-31 20:12:04',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:12:04',
                'name' => 'XL Crate',
                'short_desc' => 'XL Crate',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '3',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:12:04',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            2 => 
            array (
                'brand_id' => 1,
                'code' => 'lw',
                'created_at' => '2019-12-31 20:12:39',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:12:39',
                'name' => 'Large Wheel',
                'short_desc' => 'large wheel',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '5',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:12:39',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            3 => 
            array (
                'brand_id' => 1,
                'code' => 'xlw',
                'created_at' => '2019-12-31 20:13:02',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:13:02',
                'name' => 'XL Wheel',
                'short_desc' => 'xlw',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '7',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:13:02',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            4 => 
            array (
                'brand_id' => 1,
                'code' => 'wr',
                'created_at' => '2019-12-31 20:13:37',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:13:37',
                'name' => 'Wardrobe',
                'short_desc' => 'wardrobe',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '8',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:13:37',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            5 => 
            array (
                'brand_id' => 1,
                'code' => 'ht',
                'created_at' => '2019-12-31 20:14:07',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 6,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:14:07',
                'name' => 'Hand Truck',
                'short_desc' => 'Hand Truck',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '10',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:14:07',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            6 => 
            array (
                'brand_id' => 1,
                'code' => 'lss',
                'created_at' => '2019-12-31 20:14:39',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 7,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:14:39',
                'name' => 'Lifting Strap Set',
                'short_desc' => 'Lifting Strap Set',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '3',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:14:39',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            7 => 
            array (
                'brand_id' => 1,
                'code' => 'fb',
                'created_at' => '2019-12-31 20:15:40',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 8,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:15:40',
            'name' => 'File Bars (Add to Large Crates)',
                'short_desc' => 'File Bars to add to Large Crates',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '1',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:15:40',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            8 => 
            array (
                'brand_id' => 1,
                'code' => 'bw',
                'created_at' => '2019-12-31 20:16:07',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 9,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:16:07',
                'name' => 'Bubble Wrap',
                'short_desc' => 'bubble wrap',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '8.50',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:16:07',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            9 => 
            array (
                'brand_id' => 1,
                'code' => 'pw',
                'created_at' => '2019-12-31 20:16:33',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 10,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:16:33',
                'name' => 'Paper Wrap',
                'short_desc' => 'paper wrap',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '11',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:16:33',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            10 => 
            array (
                'brand_id' => 1,
                'code' => 'zt',
                'created_at' => '2019-12-31 20:17:39',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 11,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:17:39',
                'name' => 'Zip Ties',
                'short_desc' => 'Zip Ties $3 per bundle of 50.',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '3',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:17:39',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            11 => 
            array (
                'brand_id' => 1,
                'code' => 'sz',
                'created_at' => '2019-12-31 20:18:09',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 12,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:18:09',
                'name' => 'Serial Zips',
                'short_desc' => 'Serial Zips',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '0.50',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:18:09',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            12 => 
            array (
                'brand_id' => 1,
                'code' => 'lb',
                'created_at' => '2019-12-31 20:18:35',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 13,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:18:35',
                'name' => 'Laundry Bag',
                'short_desc' => 'Laundry Bag',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '8',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:18:35',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
            13 => 
            array (
                'brand_id' => 1,
                'code' => 'label',
                'created_at' => '2019-12-31 20:19:00',
                'deleted_at' => NULL,
                'has_color' => 1,
                'has_size' => 1,
                'id' => 14,
                'is_active' => 0,
                'is_deleted' => 0,
                'manufacture_date' => '2019-12-31 20:19:00',
                'name' => 'Labels',
                'short_desc' => 'labels',
                'sub_title' => NULL,
                'title' => NULL,
                'unit_price_label' => '0',
                'unit_quantity' => NULL,
                'updated_at' => '2019-12-31 20:19:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'weight' => NULL,
                'weight_type' => NULL,
            ),
        ));
        
        
    }
}