<?php

use Illuminate\Database\Seeder;

class ValidationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        \DB::table('validations')->delete();
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        \DB::table('validations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'section_id' => 1,
                'section' => 'validation',
                'code' => 'Add_validation_form',
                'value' => 'code:required,value:required',
                'description' => 'Code and value field required in validation form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => 10,
                'deleted_at' => '2019-09-24 14:08:32',
                'created_at' => NULL,
                'updated_at' => '2019-09-30 15:13:35',
            ),
            1 => 
            array (
                'id' => 2,
                'section_id' => 2,
                'section' => 'role',
                'code' => 'pages_form',
                'value' => 'page_name:required',
                'description' => 'add new page',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-09-30 17:26:06',
            ),
            2 => 
            array (
                'id' => 3,
                'section_id' => 3,
                'section' => 'site setting',
                'code' => 'site_form',
                'value' => 'field:required',
                'description' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => NULL,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'section_id' => 1,
                'section' => 'validations',
                'code' => 'Update_validation_form',
                'value' => 'code:required,value:required',
                'description' => 'Reset form validation',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-26 13:22:21',
                'updated_at' => '2019-09-30 14:13:16',
            ),
            4 => 
            array (
                'id' => 5,
                'section_id' => 4,
                'section' => 'Menu',
                'code' => 'menucreate',
                'value' => 'name:required,parent_id:nullable|numeric,icon:nullable,seq:nullable|numeric',
                'description' => 'tet',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 19:52:10',
                'updated_at' => '2019-12-31 11:18:35',
            ),
            5 => 
            array (
                'id' => 6,
                'section_id' => 4,
                'section' => 'Menu',
                'code' => 'add_validation_form',
                'value' => 'code:required|value:required',
                'description' => 'validation Form required field',
                'is_active' => 0,
                'is_deleted' => 1,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => 10,
                'deleted_at' => '2019-09-30 13:27:49',
                'created_at' => '2019-09-30 13:12:31',
                'updated_at' => '2019-09-30 13:27:49',
            ),
            6 => 
            array (
                'id' => 7,
                'section_id' => 1,
                'section' => 'validations',
                'code' => 'asasas',
                'value' => 'asas',
                'description' => 'asa',
                'is_active' => 0,
                'is_deleted' => 1,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => 10,
                'deleted_at' => '2019-09-30 15:14:37',
                'created_at' => '2019-09-30 15:14:33',
                'updated_at' => '2019-09-30 15:14:37',
            ),
            7 => 
            array (
                'id' => 8,
                'section_id' => 1,
                'section' => 'validations',
                'code' => 'add_section_modal_form',
                'value' => 'section:required',
                'description' => 'Add new section',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 15:31:05',
                'updated_at' => '2019-09-30 15:31:05',
            ),
            8 => 
            array (
                'id' => 9,
                'section_id' => 1,
                'section' => 'Validation',
                'code' => 'update_validation_section_form',
                'value' => 'section:required',
                'description' => 'edit section field',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 16:57:35',
                'updated_at' => '2019-09-30 16:57:35',
            ),
            9 => 
            array (
                'id' => 10,
                'section_id' => 2,
                'section' => 'Role and Permission',
                'code' => 'edit_page_form',
                'value' => 'page_name:required',
                'description' => 'edit page',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 17:30:20',
                'updated_at' => '2019-09-30 17:30:20',
            ),
            10 => 
            array (
                'id' => 11,
                'section_id' => 2,
                'section' => 'Role and Permission',
                'code' => 'role_edit_form',
                'value' => 'role_name:required',
                'description' => 'edit role form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 17:37:55',
                'updated_at' => '2019-09-30 17:37:55',
            ),
            11 => 
            array (
                'id' => 12,
                'section_id' => 2,
                'section' => 'Role and Permission',
                'code' => 'add_role_form',
                'value' => 'role_name:required',
                'description' => 'Add role form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 17:41:15',
                'updated_at' => '2019-09-30 17:46:47',
            ),
            12 => 
            array (
                'id' => 13,
                'section_id' => 2,
                'section' => 'Role and Permission',
                'code' => 'permission_form',
                'value' => 'permission_name:required',
                'description' => 'Add permission form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 17:48:22',
                'updated_at' => '2019-09-30 17:48:22',
            ),
            13 => 
            array (
                'id' => 14,
                'section_id' => 2,
                'section' => 'Role and Permission',
                'code' => 'edit_permission_form',
                'value' => 'permission_name:required',
                'description' => 'Edit permission Form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 17:54:50',
                'updated_at' => '2019-09-30 17:54:50',
            ),
            14 => 
            array (
                'id' => 15,
                'section_id' => 2,
                'section' => 'Role and Permission',
                'code' => 'sitesetting_form',
                'value' => 'code:required,value:required',
                'description' => 'Add site setting form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 18:00:03',
                'updated_at' => '2019-09-30 18:00:15',
            ),
            15 => 
            array (
                'id' => 16,
                'section_id' => 6,
                'section' => 'Users Control',
                'code' => 'users_form',
                'value' => 'FirstName:required,LastName:required,username:required,email:required,password:required|min-6|confirmed,password_confirmation:required,PhoneNumber:required,role:required',
                'description' => 'Add new user form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 18:13:40',
                'updated_at' => '2019-10-03 16:30:57',
            ),
            16 => 
            array (
                'id' => 17,
                'section_id' => 6,
                'section' => 'Users Control',
                'code' => 'edit_users_form',
                'value' => 'FirstName:required,LastName:required,username:required,email:required,PhoneNumber:required',
                'description' => 'Edit user control form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 18:54:07',
                'updated_at' => '2019-09-30 18:58:11',
            ),
            17 => 
            array (
                'id' => 18,
                'section_id' => 7,
                'section' => 'Membership',
                'code' => 'add_membership_form',
                'value' => 'asassasas',
                'description' => 'add membership form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 19:09:26',
                'updated_at' => '2019-10-03 17:50:30',
            ),
            18 => 
            array (
                'id' => 19,
                'section_id' => 8,
                'section' => 'Lookups',
                'code' => 'add_lookup_form',
                'value' => 'code:required,value:required',
                'description' => 'Add lookups form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 19:19:17',
                'updated_at' => '2019-09-30 19:19:17',
            ),
            19 => 
            array (
                'id' => 20,
                'section_id' => 8,
                'section' => 'Lookups',
                'code' => 'add_lookup_section',
                'value' => 'section:required',
                'description' => 'Add look up section form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 19:24:47',
                'updated_at' => '2019-09-30 19:24:47',
            ),
            20 => 
            array (
                'id' => 21,
                'section_id' => 8,
                'section' => 'Lookups',
                'code' => 'edit_lookup_form',
                'value' => 'code:required,value:required',
                'description' => 'Edit look up form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-09-30 19:31:06',
                'updated_at' => '2019-09-30 19:31:06',
            ),
            21 => 
            array (
                'id' => 22,
                'section_id' => 9,
                'section' => 'Note',
                'code' => 'noteCreate',
                'value' => 'title:required,status:required,priority:required,reminder_date:required,todo_date:required',
                'description' => 'Add note form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-02 17:11:50',
                'updated_at' => '2019-10-02 17:11:50',
            ),
            22 => 
            array (
                'id' => 23,
                'section_id' => 9,
                'section' => 'Note',
                'code' => 'noteUpdate',
                'value' => 'title:required,status:required,priority:required,reminder_date:required,todo_date:required',
                'description' => 'Edit Note Form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-02 19:40:58',
                'updated_at' => '2019-10-02 19:40:58',
            ),
            23 => 
            array (
                'id' => 24,
                'section_id' => 10,
                'section' => 'Icon',
                'code' => 'icon',
                'value' => 'icon_group:required,icon_name:required,icon_class:required',
                'description' => 'Icon Create form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-03 15:28:01',
                'updated_at' => '2019-10-03 15:28:01',
            ),
            24 => 
            array (
                'id' => 25,
                'section_id' => 6,
                'section' => 'Users Control',
                'code' => 'add_membership_form',
                'value' => 'id_card_no:required',
                'description' => NULL,
                'is_active' => 0,
                'is_deleted' => 1,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => 10,
                'deleted_at' => '2019-10-03 16:59:57',
                'created_at' => '2019-10-03 16:59:34',
                'updated_at' => '2019-10-03 16:59:57',
            ),
            25 => 
            array (
                'id' => 26,
                'section_id' => 11,
                'section' => 'User Profile',
                'code' => 'edit_personal_profile_form',
                'value' => 'first_name:required,last_name:required,email:required,mobile_no:required',
                'description' => 'Profile Edit form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-03 17:32:13',
                'updated_at' => '2019-10-03 17:50:59',
            ),
            26 => 
            array (
                'id' => 27,
                'section_id' => 7,
                'section' => 'Membership',
                'code' => 'edit_membership_form',
                'value' => 'id_card_type:required,id_card_no:required,issued_place:required,issued_date:required,exp_date:required,issue_authority:required',
                'description' => 'Edit membership form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 10,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-03 18:06:57',
                'updated_at' => '2019-10-03 18:06:57',
            ),
            27 => 
            array (
                'id' => 28,
                'section_id' => 12,
                'section' => 'Template',
                'code' => 'addTemplateForm',
                'value' => 'name:required,url:required,site_name:required',
                'description' => 'add template form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 2,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-31 18:41:23',
                'updated_at' => '2019-10-31 18:41:23',
            ),
            28 => 
            array (
                'id' => 29,
                'section_id' => 12,
                'section' => 'Template',
                'code' => 'editTemplateForm',
                'value' => 'name:required,url:required,site_name:required',
                'description' => 'edit template form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 2,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-31 18:58:58',
                'updated_at' => '2019-10-31 18:58:58',
            ),
            29 => 
            array (
                'id' => 30,
                'section_id' => 12,
                'section' => 'Template',
                'code' => 'add_cms_menu_form',
                'value' => 'name:required',
                'description' => 'add cms menu form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 2,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-31 19:18:53',
                'updated_at' => '2019-11-20 14:56:11',
            ),
            30 => 
            array (
                'id' => 31,
                'section_id' => 12,
                'section' => 'Template',
                'code' => 'edit_cms_menu_form',
                'value' => 'name:required',
                'description' => 'edit cms menu form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 2,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-31 19:34:26',
                'updated_at' => '2019-11-20 14:56:35',
            ),
            31 => 
            array (
                'id' => 32,
                'section_id' => 12,
                'section' => 'Template',
                'code' => 'add_cms_page_form',
                'value' => 'page_name:required',
                'description' => 'add cms page form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 2,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-31 19:39:14',
                'updated_at' => '2019-11-20 14:56:22',
            ),
            32 => 
            array (
                'id' => 33,
                'section_id' => 12,
                'section' => 'Template',
                'code' => 'edit_cms_page_form',
                'value' => 'page_name:required',
                'description' => 'edit page form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 2,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-31 19:43:38',
                'updated_at' => '2019-11-20 14:56:43',
            ),
            33 => 
            array (
                'id' => 34,
                'section_id' => 12,
                'section' => 'Template',
                'code' => 'addPostForm',
                'value' => 'title:required',
                'description' => 'add post form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 2,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-31 19:47:24',
                'updated_at' => '2019-10-31 19:47:24',
            ),
            34 => 
            array (
                'id' => 35,
                'section_id' => 12,
                'section' => 'Template',
                'code' => 'editPostForm',
                'value' => 'title:required',
                'description' => 'Edit CMS post form.',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 17,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-10-31 20:03:33',
                'updated_at' => '2019-10-31 20:03:33',
            ),
            35 => 
            array (
                'id' => 36,
                'section_id' => 12,
                'section' => 'Email Template',
                'code' => 'email_template_form',
                'value' => 'section:required,temp_code:required,temp_name:required,temp_type:required,temp_html:required',
                'description' => 'Required Fields',
                'is_active' => 1,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => 1,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-03-27 21:06:31',
                'updated_at' => '2018-06-22 21:13:25',
            ),
            36 => 
            array (
                'id' => 37,
                'section_id' => 14,
                'section' => 'Account',
                'code' => 'add_accounts_form',
                'value' => 'company_name:required,add1:required,city:required,state:required,zip:required',
                'description' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-12-31 13:39:24',
                'updated_at' => '2020-01-03 17:42:30',
            ),
            37 => 
            array (
                'id' => 38,
                'section_id' => 14,
                'section' => 'Account',
                'code' => 'add_member_form',
                'value' => 'fname:required,lname:required,email:unique-clients',
                'description' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-03 17:46:29',
                'updated_at' => '2020-01-14 19:47:08',
            ),
            38 => 
            array (
                'id' => 39,
                'section_id' => 14,
                'section' => 'Account',
                'code' => 'edit_client_form',
                'value' => 'fname:required,lname:required',
                'description' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-09 15:25:35',
                'updated_at' => '2020-01-10 18:19:34',
            ),
            39 => 
            array (
                'id' => 40,
                'section_id' => 14,
                'section' => 'Account',
                'code' => 'update_account_general_form',
                'value' => 'company_name:required,add1:required,city:required,state:required,zip:required',
                'description' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-09 16:36:28',
                'updated_at' => '2020-01-09 16:36:28',
            ),
            40 => 
            array (
                'id' => 41,
                'section_id' => 14,
                'section' => 'Account',
                'code' => 'add_client_form',
                'value' => 'fname:required,lname:required,email:unique-clients',
                'description' => NULL,
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-10 18:05:32',
                'updated_at' => '2020-01-10 18:19:26',
            ),
            41 => 
            array (
                'id' => 47,
                'section_id' => 18,
                'section' => 'Zip',
                'code' => 'zip_form',
                'value' => 'city.*:required,county.*:required,state.*:required,zipcode.*:required,price.*:required',
                'description' => 'add zip codes validation',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-21 13:40:36',
                'updated_at' => '2020-01-21 13:43:53',
            ),
            42 => 
            array (
                'id' => 48,
                'section_id' => 18,
                'section' => 'Zip',
                'code' => 'update_zip_form',
                'value' => 'city:required,county:required,state:required,zipcode:required,price:required',
                'description' => 'update zip form validation',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-21 13:44:46',
                'updated_at' => '2020-01-21 13:44:46',
            ),
            43 => 
            array (
                'id' => 49,
                'section_id' => 19,
                'section' => 'Faq',
                'code' => 'faqs_form',
                'value' => 'sequence:required,question:required,answer:required',
                'description' => 'add faqs validation',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-21 18:35:13',
                'updated_at' => '2020-01-21 18:35:13',
            ),
            44 => 
            array (
                'id' => 50,
                'section_id' => 19,
                'section' => 'Faq',
                'code' => 'update_faqs_form',
                'value' => 'sequence:required,question:required,answer:required',
                'description' => 'update faqs form',
                'is_active' => 0,
                'is_deleted' => 0,
                'userc_id' => 1,
                'useru_id' => NULL,
                'userd_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2020-01-21 18:43:35',
                'updated_at' => '2020-01-21 18:43:35',
            ),
        ));
        
        
    }
}