<?php

use Illuminate\Database\Seeder;

class ZipCodesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('zip_codes')->delete();
        
        \DB::table('zip_codes')->insert(array (
            0 => 
            array (
                'city' => 'Driftwood',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:26',
                'deleted_at' => NULL,
                'id' => 1,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:26',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78619,
            ),
            1 => 
            array (
                'city' => 'Mount Sharp',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:27',
                'deleted_at' => NULL,
                'id' => 2,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:27',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78620,
            ),
            2 => 
            array (
                'city' => 'Henly ',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:27',
                'deleted_at' => NULL,
                'id' => 3,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:27',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78620,
            ),
            3 => 
            array (
                'city' => 'Dripping Springs',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:27',
                'deleted_at' => NULL,
                'id' => 4,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:27',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78620,
            ),
            4 => 
            array (
                'city' => 'Uhland',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:27',
                'deleted_at' => NULL,
                'id' => 5,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:27',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78640,
            ),
            5 => 
            array (
                'city' => 'Pironeer Town',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:27',
                'deleted_at' => NULL,
                'id' => 6,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:27',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78676,
            ),
            6 => 
            array (
                'city' => 'Woodcreek',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:27',
                'deleted_at' => NULL,
                'id' => 7,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:27',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78676,
            ),
            7 => 
            array (
                'city' => 'Wimberley',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:27',
                'deleted_at' => NULL,
                'id' => 8,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:27',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78676,
            ),
            8 => 
            array (
                'city' => 'Buda',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:27',
                'deleted_at' => NULL,
                'id' => 9,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:27',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78610,
            ),
            9 => 
            array (
                'city' => 'Creedmoor',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:28',
                'deleted_at' => NULL,
                'id' => 10,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:28',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78610,
            ),
            10 => 
            array (
                'city' => 'Mountain City',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:28',
                'deleted_at' => NULL,
                'id' => 11,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:28',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78610,
            ),
            11 => 
            array (
                'city' => 'Kyle',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:28',
                'deleted_at' => NULL,
                'id' => 12,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:28',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78640,
            ),
            12 => 
            array (
                'city' => 'Niederwald',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:28',
                'deleted_at' => NULL,
                'id' => 13,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:28',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78640,
            ),
            13 => 
            array (
                'city' => 'San Marcos',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:28',
                'deleted_at' => NULL,
                'id' => 14,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:28',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78666,
            ),
            14 => 
            array (
                'city' => 'Austin ',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:28',
                'deleted_at' => NULL,
                'id' => 15,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:28',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78737,
            ),
            15 => 
            array (
                'city' => 'San Marcos',
                'county' => 'Hays',
                'created_at' => '2020-01-07 16:48:28',
                'deleted_at' => NULL,
                'id' => 16,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:48:28',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78667,
            ),
            16 => 
            array (
                'city' => 'Andice',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:56',
                'deleted_at' => NULL,
                'id' => 17,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:56',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78628,
            ),
            17 => 
            array (
                'city' => 'Beyersville ',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:56',
                'deleted_at' => NULL,
                'id' => 18,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:56',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78615,
            ),
            18 => 
            array (
                'city' => 'Coupland',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:56',
                'deleted_at' => NULL,
                'id' => 19,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:56',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78615,
            ),
            19 => 
            array (
                'city' => 'Florence',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:56',
                'deleted_at' => NULL,
                'id' => 20,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:56',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76527,
            ),
            20 => 
            array (
                'city' => 'Frame Switch',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:56',
                'deleted_at' => NULL,
                'id' => 21,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:56',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            21 => 
            array (
                'city' => 'Friendship',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:57',
                'deleted_at' => NULL,
                'id' => 22,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:57',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76530,
            ),
            22 => 
            array (
                'city' => 'Granger',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:57',
                'deleted_at' => NULL,
                'id' => 23,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:57',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76530,
            ),
            23 => 
            array (
                'city' => 'Hare',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:57',
                'deleted_at' => NULL,
                'id' => 24,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:57',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            24 => 
            array (
                'city' => 'Hoxie',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:57',
                'deleted_at' => NULL,
                'id' => 25,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:57',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            25 => 
            array (
                'city' => 'Jarrel',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:57',
                'deleted_at' => NULL,
                'id' => 26,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:57',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76537,
            ),
            26 => 
            array (
                'city' => 'jonah',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:57',
                'deleted_at' => NULL,
                'id' => 27,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:57',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 788626,
            ),
            27 => 
            array (
                'city' => 'Laneport',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:57',
                'deleted_at' => NULL,
                'id' => 28,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:57',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            28 => 
            array (
                'city' => 'New Corn Hill',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:57',
                'deleted_at' => NULL,
                'id' => 29,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:57',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76537,
            ),
            29 => 
            array (
                'city' => 'Noack',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:57',
                'deleted_at' => NULL,
                'id' => 30,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:57',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            30 => 
            array (
                'city' => 'Normans Crossing ',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 31,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            31 => 
            array (
                'city' => 'Rices Crossing ',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 32,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            32 => 
            array (
                'city' => 'Sandoval',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 33,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            33 => 
            array (
                'city' => 'Schwertner',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 34,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76573,
            ),
            34 => 
            array (
                'city' => 'Taylor',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 35,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            35 => 
            array (
                'city' => 'Theon',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 36,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76537,
            ),
            36 => 
            array (
                'city' => 'Thrall',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 37,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76578,
            ),
            37 => 
            array (
                'city' => 'Three point',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 38,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78664,
            ),
            38 => 
            array (
                'city' => 'Walburg',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 39,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78673,
            ),
            39 => 
            array (
                'city' => 'Waterloo',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 40,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 76574,
            ),
            40 => 
            array (
                'city' => 'Weir',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:58',
                'deleted_at' => NULL,
                'id' => 41,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:58',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78674,
            ),
            41 => 
            array (
                'city' => 'Austin',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 42,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78717,
            ),
            42 => 
            array (
                'city' => 'Austin',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 43,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78729,
            ),
            43 => 
            array (
                'city' => 'Brushy Creek',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 44,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78717,
            ),
            44 => 
            array (
                'city' => 'Cedar pack',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 45,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78613,
            ),
            45 => 
            array (
                'city' => 'Cedar pack',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 46,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78630,
            ),
            46 => 
            array (
                'city' => 'Dell Computers',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 47,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78682,
            ),
            47 => 
            array (
                'city' => 'Georgetown',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 48,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78626,
            ),
            48 => 
            array (
                'city' => 'Georgetown',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 49,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78627,
            ),
            49 => 
            array (
                'city' => 'Georgetown',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 50,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78628,
            ),
            50 => 
            array (
                'city' => 'Georgetown',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 51,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78633,
            ),
            51 => 
            array (
                'city' => 'Hutto',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:49:59',
                'deleted_at' => NULL,
                'id' => 52,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:49:59',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78634,
            ),
            52 => 
            array (
                'city' => 'Jollyville',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 53,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78729,
            ),
            53 => 
            array (
                'city' => 'Leander',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 54,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78641,
            ),
            54 => 
            array (
                'city' => 'Leander',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 55,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78646,
            ),
            55 => 
            array (
                'city' => 'Liberty Hill',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 56,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78642,
            ),
            56 => 
            array (
                'city' => 'Old round Rock',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 57,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78664,
            ),
            57 => 
            array (
                'city' => 'Round Rock',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 58,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78664,
            ),
            58 => 
            array (
                'city' => 'Round Rock',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 59,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78665,
            ),
            59 => 
            array (
                'city' => 'Round Rock',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 60,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78680,
            ),
            60 => 
            array (
                'city' => 'Round Rock',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 61,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78681,
            ),
            61 => 
            array (
                'city' => 'Round Rock',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:00',
                'deleted_at' => NULL,
                'id' => 62,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:00',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78682,
            ),
            62 => 
            array (
                'city' => 'Round Rock',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:01',
                'deleted_at' => NULL,
                'id' => 63,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:01',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78683,
            ),
            63 => 
            array (
                'city' => 'Volente',
                'county' => 'Williamson ',
                'created_at' => '2020-01-07 16:50:01',
                'deleted_at' => NULL,
                'id' => 64,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX)',
                'updated_at' => '2020-01-07 16:50:01',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78641,
            ),
            64 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:17',
                'deleted_at' => NULL,
                'id' => 65,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:17',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 73301,
            ),
            65 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:17',
                'deleted_at' => NULL,
                'id' => 66,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:17',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 73344,
            ),
            66 => 
            array (
                'city' => 'Del Valle',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:17',
                'deleted_at' => NULL,
                'id' => 67,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:17',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78617,
            ),
            67 => 
            array (
                'city' => 'Leander',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:17',
                'deleted_at' => NULL,
                'id' => 68,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:17',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78645,
            ),
            68 => 
            array (
                'city' => 'Mc Neil',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:17',
                'deleted_at' => NULL,
                'id' => 69,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:17',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78651,
            ),
            69 => 
            array (
                'city' => 'Manchaca',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:17',
                'deleted_at' => NULL,
                'id' => 70,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:17',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78652,
            ),
            70 => 
            array (
                'city' => 'Pflugerville',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:17',
                'deleted_at' => NULL,
                'id' => 71,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:17',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78660,
            ),
            71 => 
            array (
                'city' => 'Manor',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:17',
                'deleted_at' => NULL,
                'id' => 72,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:17',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78653,
            ),
            72 => 
            array (
                'city' => 'Spicewood',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 73,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78669,
            ),
            73 => 
            array (
                'city' => 'Pflugerville',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 74,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78691,
            ),
            74 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 75,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78701,
            ),
            75 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 76,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78702,
            ),
            76 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 77,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78703,
            ),
            77 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 78,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78704,
            ),
            78 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 79,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78705,
            ),
            79 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 80,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78708,
            ),
            80 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 81,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78709,
            ),
            81 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 82,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78710,
            ),
            82 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 83,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78711,
            ),
            83 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:18',
                'deleted_at' => NULL,
                'id' => 84,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:18',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78712,
            ),
            84 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 85,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78713,
            ),
            85 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 86,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78714,
            ),
            86 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 87,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78715,
            ),
            87 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 88,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78716,
            ),
            88 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 89,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78718,
            ),
            89 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 90,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78719,
            ),
            90 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 91,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78720,
            ),
            91 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 92,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78721,
            ),
            92 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 93,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78722,
            ),
            93 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 94,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78723,
            ),
            94 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 95,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78724,
            ),
            95 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:19',
                'deleted_at' => NULL,
                'id' => 96,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:19',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78725,
            ),
            96 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 97,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78726,
            ),
            97 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 98,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78727,
            ),
            98 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 99,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78728,
            ),
            99 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 100,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78730,
            ),
            100 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 101,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78731,
            ),
            101 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 102,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78732,
            ),
            102 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 103,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78733,
            ),
            103 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 104,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78734,
            ),
            104 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 105,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78735,
            ),
            105 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 106,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78736,
            ),
            106 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 107,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78738,
            ),
            107 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 108,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78739,
            ),
            108 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:20',
                'deleted_at' => NULL,
                'id' => 109,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:20',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78741,
            ),
            109 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 110,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78742,
            ),
            110 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 111,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78744,
            ),
            111 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 112,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78745,
            ),
            112 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 113,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78746,
            ),
            113 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 114,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78747,
            ),
            114 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 115,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78748,
            ),
            115 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 116,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78749,
            ),
            116 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 117,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78750,
            ),
            117 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 118,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78751,
            ),
            118 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:21',
                'deleted_at' => NULL,
                'id' => 119,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:21',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78752,
            ),
            119 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:22',
                'deleted_at' => NULL,
                'id' => 120,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:22',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78753,
            ),
            120 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:22',
                'deleted_at' => NULL,
                'id' => 121,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:22',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78754,
            ),
            121 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:22',
                'deleted_at' => NULL,
                'id' => 122,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:22',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78755,
            ),
            122 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:22',
                'deleted_at' => NULL,
                'id' => 123,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:22',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78756,
            ),
            123 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:22',
                'deleted_at' => NULL,
                'id' => 124,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:22',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78757,
            ),
            124 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:22',
                'deleted_at' => NULL,
                'id' => 125,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:22',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78758,
            ),
            125 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:22',
                'deleted_at' => NULL,
                'id' => 126,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:22',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78759,
            ),
            126 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:22',
                'deleted_at' => NULL,
                'id' => 127,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:22',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78760,
            ),
            127 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:22',
                'deleted_at' => NULL,
                'id' => 128,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:22',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78761,
            ),
            128 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:23',
                'deleted_at' => NULL,
                'id' => 129,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:23',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78762,
            ),
            129 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:23',
                'deleted_at' => NULL,
                'id' => 130,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:23',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78763,
            ),
            130 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:23',
                'deleted_at' => NULL,
                'id' => 131,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:23',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78764,
            ),
            131 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:23',
                'deleted_at' => NULL,
                'id' => 132,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:23',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78765,
            ),
            132 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:23',
                'deleted_at' => NULL,
                'id' => 133,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:23',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78766,
            ),
            133 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:23',
                'deleted_at' => NULL,
                'id' => 134,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:23',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78767,
            ),
            134 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:23',
                'deleted_at' => NULL,
                'id' => 135,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:23',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78768,
            ),
            135 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:23',
                'deleted_at' => NULL,
                'id' => 136,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:23',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78769,
            ),
            136 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:23',
                'deleted_at' => NULL,
                'id' => 137,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:23',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78772,
            ),
            137 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 138,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78773,
            ),
            138 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 139,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78774,
            ),
            139 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 140,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78778,
            ),
            140 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 141,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78779,
            ),
            141 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 142,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78780,
            ),
            142 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 143,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78781,
            ),
            143 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 144,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78783,
            ),
            144 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 145,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78787,
            ),
            145 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 146,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78798,
            ),
            146 => 
            array (
                'city' => 'Austin ',
                'county' => 'Travis',
                'created_at' => '2020-01-07 16:50:24',
                'deleted_at' => NULL,
                'id' => 147,
                'is_active' => 0,
                'is_deleted' => 0,
            'state' => 'Texas (TX) ',
                'updated_at' => '2020-01-07 16:50:24',
                'userc_id' => 1,
                'userd_id' => NULL,
                'useru_id' => NULL,
                'zipcode' => 78799,
            ),
        ));
        
        
    }
}