module.exports = {
    styles: [
        "resources/assets/cratesSkates/css/fontawesome.css",
        "resources/assets/cratesSkates/css/slick.css",
        "resources/assets/cratesSkates/css/jquery-ui.min.css",
        "resources/assets/cratesSkates/css/slick-theme.css",
        "resources/assets/cratesSkates/css/animate.css",
        "resources/assets/cratesSkates/css/themify-icons.css",
        "resources/assets/cratesSkates/css/bootstrap.css",
        "resources/assets/cratesSkates/css/magnific-popup.css",
        "resources/assets/cratesSkates/css/date-picker.css",
        "resources/assets/cratesSkates/css/select2.css",

        'node_modules/bootstrap-daterangepicker/daterangepicker.css',
        'node_modules/toastr/build/toastr.min.css',

        // "node_modules/select2/dist/css/select2.css",
        "resources/assets/cratesOnSkates/custom/css/animate.css",
        "resources/assets/cratesOnSkates/custom/css/home_page.css",
        "resources/assets/cratesOnSkates/custom/css/residential.css",
        "resources/assets/cratesOnSkates/custom/css/product.css",
        "resources/assets/cratesOnSkates/custom/css/order_now.css",
        "resources/assets/cratesOnSkates/custom/css/font.css",
        "resources/assets/cratesOnSkates/custom/css/checkout_page.css",
        "resources/assets/cratesSkates/css/color3.css",
        "resources/assets/cratesOnSkates/custom/css/footer.css",
        "resources/assets/smart-wizard/css/smart_wizard.min.css",
        "resources/assets/smart-wizard/css/smart_wizard_theme_dots.css",
        "resources/assets/smart-wizard/css/smart_wizard_theme_circles.min.css",
        "resources/assets/cratesOnSkates/custom/css/cos-index.css",

    ],
    scripts: [
        "resources/assets/cratesSkates/js/jquery-3.3.1.min.js",
        "resources/assets/cratesSkates/js/jquery-ui.min.js",
        // 'node_modules/jquery/dist/jquery.min.js',
        // 'node_modules/inputmask/dist/inputmask/jquery.inputmask.js',
        "resources/assets/cratesSkates/js/jquery.magnific-popup.js",
        // 'resources/assets/cratesSkates/js/zoom-gallery.js',
        "resources/assets/cratesSkates/js/menu.js",
        "resources/assets/cratesSkates/js/lazysizes.min.js",
        "resources/assets/cratesSkates/js/popper.min.js",
        "resources/assets/cratesSkates/js/slick.js",
        "node_modules/@fortawesome/fontawesome-free/js/all.min.js",
        "resources/assets/cratesSkates/js/bootstrap.js",
        "resources/assets/cratesSkates/js/bootstrap-notify.js",
        "resources/assets/cratesSkates/js/searchLayout.js",
        "resources/assets/cratesSkates/js/jquery.elevatezoom.js",
        "resources/assets/cratesSkates/js/select2.js",
        'node_modules/toastr/build/toastr.min.js',
        "resources/assets/cratesSkates/js/script.js",

        'node_modules/bootstrap-daterangepicker/moment.min.js',
        'node_modules/bootstrap-daterangepicker/daterangepicker.js',

        "node_modules/js-cookie/src/js.cookie.js",
        "resources/assets/cratesOnSkates/custom/js/typed.js",
        "resources/assets/cratesOnSkates/custom/js/jquery.waypoints.min.js",
        "resources/assets/cratesOnSkates/custom/js/custom_ajax.js",
        "resources/assets/cratesOnSkates/custom/js/crates_page_load.js",
        "resources/assets/cratesOnSkates/custom/js/order_now.js",
        "resources/assets/smart-wizard/js/jquery.smartWizard.min.js",
        "resources/assets/cratesOnSkates/custom/js/login.js",
        "resources/assets/cratesOnSkates/custom/js/checkout.js",
        "resources/assets/cratesOnSkates/custom/js/cos-checkout.js",
        "resources/assets/cratesOnSkates/custom/js/modal.js",
        "resources/assets/cratesOnSkates/custom/js/dashboard.js",
        "resources/assets/cratesOnSkates/custom/js/toastr.js",
        'node_modules/inputmask/dist/min/inputmask/inputmask.min.js',
        'resources/assets/supportNew/js/custom/support_modal.js',
        // 'node_modules/signature_pad/dist/signature_pad.min.js',
    ]
};