const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');

// demo 7 bulndle 


mix.scripts([
	'node_modules/@fortawesome/fontawesome-free/js/all.min.js',
	'node_modules/jquery/dist/jquery.min.js',
	'node_modules/autosize/dist/autosize.min.js',
	'node_modules/block-ui/jquery.blockUI.js',
	'node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js',
	'node_modules/bootstrap-daterangepicker/daterangepicker.js',
	'node_modules/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js',
	'node_modules/bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js',
	'node_modules/bootstrap-markdown/js/bootstrap-markdown.js',
	'node_modules/bootstrap-maxlength/bootstrap-maxlength.min.js',
	'node_modules/bootstrap-notify/bootstrap-notify.min.js',
	'node_modules/bootstrap-select/dist/js/bootstrap-select.min.js',
	'node_modules/bootstrap-switch/dist/js/bootstrap-switch.min.js',
	'node_modules/bootstrap-timepicker/js/bootstrap-timepicker.min.js',
	'node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js',
	'node_modules/chart.js/dist/Chart.bundle.min.js',
	'node_modules/clipboard/dist/clipboard.min.js',
	'node_modules/counterup/jquery.counter.min.js',
	'node_modules/datatables.net-autofill-bs4/js/autoFill.bootstrap4.min.js',
	'node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js',
	'node_modules/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js',
	'node_modules/datatables.net-colreorder-bs4/js/colReader.bootstrap4.min.js',
	'node_modules/datatables.net-fixedcolumns-bs4/js/fixedColumns.bootstrap4.min.js',
	'node_modules/datatables.net-fixedheader-bs4/js/fixedHeader.bootstrap4.min.js',
	'node_modules/datatables.net-keytable-bs4/js/keyTable.bootstrap4.min.js',
	'node_modules/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js',
	'node_modules/datatables.net-rowgroup-bs4/js/rowGroup.bootstrap4.min.js',
	'node_modules/datatables.net-rowreorder-bs4/js/rowReorder.bootstrap4.min.js',
	'node_modules/datatables.net-scroller-bs4/js/scroller.bootstrap4.min.js',
	'node_modules/datatables.net-select-bs4/js/select.bootstrap4.min.js',
	'node_modules/dompurify/dist/purify.min.js',
	'node_modules/dropzone/dist/min/dropzone.min.js',
	'node_modules/es6-promise-polyfill/promise.min.js',
	'node_modules/fullcalendar/fullcalendar.min.js',
	'node_modules/gmaps/gmaps.min.js',
	'node_modules/handlebars/dist/handlebars.min.js',
	'node_modules/inputmask/dist/min/jquery.inputmask.bundle.min.js',
	'node_modules/ion-rangeslider/js/ion.rangeSlider.min.js',
	'node_modules/jquery-flot/jquery.flot.js',
	'node_modules/jquery-form/dist/jquery.form.min.js',
	'node_modules/jquery-validation/dist/jquery.validate.min.js',
	'node_modules/jquery-repeater/jquery.repeater.min.js',
	'node_modules/jqvmap/dist/jqvmap.min.js',
	'node_modules/js-cookie/src/js.cookie.js',
	'node_modules/jstree/dist/jstree.min.js',
	'node_modules/jszip/dist/jszip.min.js',
	'node_modules/markdown/lib/markdown.js',
	'node_modules/moment/min/moment.min.js',
	'node_modules/morris.js/morris.min.js',
	'node_modules/nouislider/distribute/nouislider.min.js',
	'node_modules/owl.carousel/dist/owl.carousel.min.js',
	'node_modules/pace/pace.js',
	'node_modules/pace-js/pace.min.js',
	'node_modules/pdfmake/src/browser-extensions/pdfMake.js',
	'node_modules/perfect-scrollbar/dist/perfect-scrollbar.min.js',
	'node_modules/popper.js/dist/popper.min.js',
	'node_modules/prismjs/prismjs.js',
	'node_modules/raphael/raphael.min.js',
	'node_modules/select2/dist/js/select2.min.js',
	'node_modules/sticky.js/dist/sticky.min.js',
	'node_modules/stream-exhaust/index.js',
	'node_modules/summernote/dist/summernote.js',
	'node_modules/sweetalert2/dist/sweetalert2.min.js',
	'node_modules/tether/js/tether.min.js',
	'node_modules/toastr/build/toastr.min.js',
	'node_modules/tooltip.js/dist/tooltip.min.js',
	'node_modules/typeahead.js/dist/typeahead.bundle.min.js',
	'node_modules/underscore/underscore-min.js',
	'node_modules/waypoints/src/waypoint.js',
	'node_modules/wnumb/wNumb.js',
	], 'public/bundle.js')

mix.styles([
	'node_modules/@fortawesome/fontawesome-free/css/all.min.css',
	'node_modules/animiate.css/animate.min.css',
	'node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css',
	'node_modules/bootstrap-daterangepicker/daterangepicker.css',
	'node_modules/bootstrap-datetime-picker/css/bootstrap-datetimepicker.min.css',
	'node_modules/bootstrap-markdown/css/bootstrap-markdown.css',
	'node_modules/bootstrap-select/dist/css/bootstrap-select.min.css',
	'node_modules/bootstrap-switch/dist/css/bootstrap2/bootstrap-switch.min.css',
	'node_modules/bootstrap-timepicker/css/bootstrap-timepicker.min.css',
	'node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css',
	'node_modules/chart.js/dist/Chart.bundle.min.css',
	'node_modules/datatables.net-autofill-bs4/css/autoFill.bootstrap4.min.css',
	'node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css',
	'node_modules/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css',
	'node_modules/datatables.net-colreorder-bs4/css/colReader.bootstrap4.min.css',
	'node_modules/datatables.net-fixedcolumns-bs4/css/fixedColumns.bootstrap4.min.css',
	'node_modules/datatables.net-fixedheader-bs4/css/fixedHeader.bootstrap4.min.css',
	'node_modules/datatables.net-keytable-bs4/css/keyTable.bootstrap4.min.css',
	'node_modules/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css',
	'node_modules/datatables.net-rowgroup-bs4/css/rowGroup.bootstrap4.min.css',
	'node_modules/datatables.net-rowreorder-bs4/css/rowReorder.bootstrap4.min.css',
	'node_modules/datatables.net-scroller-bs4/css/scroller.bootstrap4.min.css',
	'node_modules/datatables.net-select-bs4/css/select.bootstrap4.min.css',
	'node_modules/dropzone/dist/min/dropzone.min.css',
	'node_modules/fullcalendar/fullcalendar.min.css',
	'node_modules/inputmask/css/inputmask.css',
	'node_modules/ion-rangeslider/css/ion.rangeSlider.min.css',
	'node_modules/jqvmap/dist/jqvmap.min.css',
	'node_modules/nouislider/distribute/nouislider.min.css',
	'node_modules/perfect-scrollbar/css/perfect-scrollbar.min.css',
	'node_modules/select2/dist/css/select2.min.css',
	'node_modules/socicon/css/socicon.css',
	'node_modules/summernote/dist/summernote.css',
	'node_modules/sweetalert2/dist/sweetalert2.min.css',
	'node_modules/tether/css/tether.min.css',
	'node_modules/toastr/build/toastr.min.css',
	], 'public/bundle.css')